### ISSUE TITLE
Login process is cumbersome

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/fabric8-ui#114]
The current (Feb 8) initial login process is cumbersome - 4 steps to login with an existing github account - see below.

Requires significant changes

**Comment by ldimaggi** [comment]
![1](https://cloud.githubusercontent.com/assets/642621/22786510/ce5282fc-eea6-11e6-8fad-dd7956ff5bb5.png)

![2](https://cloud.githubusercontent.com/assets/642621/22786508/ce3dda0a-eea6-11e6-8edc-77a9af5b7f66.png)

![3](https://cloud.githubusercontent.com/assets/642621/22786511/ce5365dc-eea6-11e6-9e82-6cbca37bf442.png)

![4](https://cloud.githubusercontent.com/assets/642621/22786509/ce473c08-eea6-11e6-9f20-f636a486df4b.png)

**Comment by joshuawilson** [comment]
@pmuir @catrobson @maxandersen who owns this task?

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#936
