### ISSUE TITLE
Deleting a space that contains workitems deletes the work items and not the space

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1197]
Steps to recreate:
* Create a new space
* In that space create one or more workitems
* Delete the space
* Logout and login to refresh all menus/lists of spaces
* The space is still there, but its workitems are gone
* The space can now be deleted

**Comment by joshuawilson** [comment]
Cool feature! I was wanting to do that earlier today.

**Comment by aslakknutsen** [comment]
I just noticed the same. This is my debug info:

Create a space, Go anywhere, Go to View All spaces, Delete created space. The rest api DELETE space is called. Logout. Notification '"SpaceName" was created!" appear. It somehow manages to call POST spaces with the same space during logout for some absurd reason. Log back in and the space is there. This time you can delete it.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#925
