### ISSUE TITLE
Add ability to have multiple Admins of a Space

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ui#1249]
When trying to add Areas to a Space, it was discovered that the creator the Space must add Collaborators/Areas (access the Settings). There should be the ability to have multiple administrators of a Space.

**Comment by joshuawilson** [comment]
This will be solved when we add Orgs and possibly need Role Based Access Control. Currently we are creating a shared space under a "user" not an "org".

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#922
