### ISSUE TITLE
Deleting a space does not delete the pipelines

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1251]
If the user attempts to access or delete a pipeline that was originally created in a space that has been deleted, this error is written to the Chrome browser console log:

```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'almusertest1/test1493928134147/create/pipelines/test1493819684996'
Error: Cannot match any routes. URL Segment: 'almusertest1/test1493928134147/create/pipelines/test1493819684996'
```

However, no error is displayed in the UI for the user.

**Comment by joshuawilson** [comment]
We need to take a deeper look at clean up when we "delete" something like a space.

**Comment by joshuawilson** [comment]
@jstrachan @rawlingsj do you know how we are doing regarding cleaning up when we delete a space?

**Comment by ldimaggi** [comment]
Closing as a dup of:  https://github.com/fabric8-ui/fabric8-ui/issues/1344
