### ISSUE TITLE
Blue links on dark background are hard to read

### ISSUE THREAD

**Issue by rkratky** [fabric8-ui/fabric8-ui#1260]
Links rendered as blue text on dark background are difficult to read. The styling should be different.

![blue-links](https://cloud.githubusercontent.com/assets/6623103/25744913/99bf5ef0-319c-11e7-9737-319d42341e6c.png)

**Comment by joshuawilson** [comment]
@catrobson @mindreeper2420 can you please take a look at this.

**Comment by catrobson** [comment]
Yup, agreed it is hard to read.  Will get visual input.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#921
