### ISSUE TITLE
Landing page misformatted in Chrome

### ISSUE THREAD

**Issue by rkratky** [fabric8-ui/fabric8-ui#1265]
Attaching screenshot of the current landing page in Blink-based browsers:

![chrome-hp](https://cloud.githubusercontent.com/assets/6623103/25772830/6361805e-3273-11e7-9967-0013ec4f57fc.png)

**Comment by joshuawilson** [comment]
@rkratky is this still an issue? If so, please describe how to reproduce it.

**Comment by rkratky** [comment]
@joshuawilson, yes, it's still an issue. To reproduce: just open in Chrome in a non-incognito window. I removed all configuration and cache and reinstalled the browser to ensure there's no plugin, extension, or history interference. The behavior is still the same.

Google Chrome, Version 58.0.3029.110 (64-bit), Fedora 25.

**Comment by joshuawilson** [comment]
@rkratky can you please specify what the issue is. I don't understand with just the title and screenshots.

**Comment by rkratky** [comment]
@joshuawilson, I've no idea what the underlying issue is. But the screenshot is an actual screenshot of the page as it shows for me -- you'll notice that it doesn't look as it's supposed to.

**Comment by joshuawilson** [comment]
@rkratky is this still an issue?

**Comment by rkratky** [comment]
@joshuawilson, yes, I'm still seeing the same thing in Chrome. Only when I'm not logged in, though.

**Comment by joshuawilson** [comment]
Oh, that is interesting. @mindreeper2420 can you please take a look at this.

**Comment by mindreeper2420** [comment]
@joshuawilson I have been unable to replicate this. I've cleared all cache, plugins, browser history. I am on Mac OSX using version 59.0.3071.115 (Official Build) (64-bit).

Here is what I see:
**Logged Out:**
<img width="1440" alt="screen shot 2017-07-28 at 5 20 44 pm" src="https://user-images.githubusercontent.com/4032718/28736738-4a24afc6-73b9-11e7-8130-0c3aeab2f6bc.png">

**Logged In:**
<img width="1440" alt="screen shot 2017-07-28 at 5 21 16 pm" src="https://user-images.githubusercontent.com/4032718/28736740-51d17556-73b9-11e7-89fc-7e0d2549e509.png">

**Comment by rkratky** [comment]
I can confirm it's showing as it's supposed to for me, too, now.
