### ISSUE TITLE
Feature request - Automated method for users to delete a project

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1284]
(And also delete all a project's assets.)

Related to:  https://github.com/fabric8io/fabric8-ui/issues/1283

**Comment by joshuawilson** [comment]
What do you mean by "project"? Is this in OpenShift or are you referring to Space?

What would the user workflow be for the scenario you listed?

**Comment by ldimaggi** [comment]
This is related to the Spaces - where the user adds a project (such as a Vert.X HTTP Booster) to a space. It should be possible for a user to delete a project and by doing so also optionally have the project's assest (pipeline, github repo, etc.) deleted.  Thx!

**Comment by joshuawilson** [comment]
I agree we need to be able to have the "delete" clean up after it's self.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#920
