### ISSUE TITLE
Profile -> update profile -> Update tenant does not work 

### ISSUE THREAD

**Issue by ibuziuk** [fabric8-ui/fabric8-ui#1311]
There are no errors / warning in browser console, just after pressing "Update tenant" button nothing happens

**Comment by joshuawilson** [comment]
@aslakknutsen are we still using the Update Tenant feature.

**Comment by joshuawilson** [comment]
@ibuziuk this works for me. I know that there is no feedback but it does update. You can verify it on OpenShift by checking the version of the tenant.

@aslakknutsen Do you plan for us to keep this button/feature or is there an automated way to handle it. If we keep it can we provide feedback to know that it was updated? Maybe display the version number.

**Comment by ibuziuk** [comment]
I pressed the button and tenant seems to be updated. However 
`oc get pod che-1-o jsonpath='{.Labels.version}'` returns 1.0.155
and the latest version now is 1.0.160

**Comment by ibuziuk** [comment]
```
I pressed the button and tenant seems to be updated. However
oc get pod che-1-o jsonpath='{.Labels.version}' returns 1.0.155
and the latest version now is 1.0.160
```
This fixed now - was able to update tenant to 1.0.60 via button

**Comment by joshuawilson** [comment]
@aslakknutsen can we get an API that will return the version? That way we can display it.

**Comment by aslakknutsen** [comment]
@joshuawilson yea, WIP

**Comment by joshuawilson** [comment]
thanks

**Comment by joshuawilson** [comment]
Clicking the button should display a dialog box stating your current tenant version and the one being upgraded OR the version they are running and that there is no update available.

@aslakknutsen is there an API for this now?

**Comment by aslakknutsen** [comment]
Closing. Update button was a temp hack during summit. To be replaced by automation.

**Comment by joshuawilson** [comment]
@aslakknutsen is the automation in place and working? Can we remove the button?

**Comment by ldimaggi** [comment]
What are the metrics regarding the automation? How often does it run? What triggers it? What information is logged where when it (tries to) runs? Thx!
