### ISSUE TITLE
Can't delete *-jenkins project in OpenShift

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1350]
_From @fbricon on May 2, 2017 18:20_

All projects can be deleted in OpenShift, except for `Project 'fbricon-jenkins'' could not be deleted.User "fbricon@redhat.com" cannot delete projects in project "fbricon-jenkins"`

Behaviour should be consistent for all OpenShift projects

_Copied from original issue: openshiftio/openshift.io#141_

**Comment by jstrachan** [comment]
the `-jenkins` + `-che` namespaces are owned by openshift.io; am not sure we should let users be able to delete them.

**Comment by joshuawilson** [comment]
@fbricon do you have thoughts/comments on this?

**Comment by fbricon** [comment]
reserved 'system' projects should probably all be protected from deletion. 
Ideally, there should be a message explaining why these projects can't be deleted

**Comment by joshuawilson** [comment]
@fbricon did you get this error in OpenShift? If so, isn't this an OpenShift issue?

**Comment by joshuawilson** [comment]
I just deleted my -jenkins from OSO. However when I updated my tenant it came back. 
@jstrachan What should the actions be here?
@fbricon can we close this?

**Comment by joshuawilson** [comment]
I'm closing this as it isn't an issue for OSIO but for OSO. Please comment as needed.

**Comment by ldimaggi** [comment]
FYI - I think that the issue here is that the projects' github repos were not deleted - and the webhooks defined for these repos resulted in the projects being recreated.

**Comment by joshuawilson** [comment]
While that may be true, what does it have to do with granting permissions to delete something in OSO?
