### ISSUE TITLE
No way to recover from  *cough* accidental *cough* OpenShift project deletion

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1352]
_From @fbricon on May 2, 2017 19:4_

Because this user doesn't know what he's doing, (following #130 and #141), some critical, missing OpenShift projects prevent new spaces from being operational, even though a git project was successfully created

<img width="469" alt="screen shot 2017-05-02 at 2 56 27 pm" src="https://cloud.githubusercontent.com/assets/148698/25634320/23fb470c-2f48-11e7-9803-f3e5b47e0839.png">

Either openshift.io should be able to recover from that state (recreate the missing openshift projects) or prevent these projects from being "accidentally" deleted.
  

_Copied from original issue: openshiftio/openshift.io#143_

**Comment by joshuawilson** [comment]
@ldimaggi can you try to reproduce this please?
cc @jstrachan @rawlingsj @corinnekrych

**Comment by ldimaggi** [comment]
I have seen that error message - not sure about how to recreate it. Will keep an eye open for it.

**Comment by aslakknutsen** [comment]
You get this error when you Delete your OSO namespaces. Tenant services do not monitor them to auto recreate. This is partly related to https://github.com/openshiftio/openshift.io/issues/297 which would stop you from being allowed to, but you're still admin of a couple of them and have the rights to delete.

Calling PATCH core/api/user/services will trigger a recreate/update, but not sure where that should happen. Ideally we would lock down the resource on oso we require and not allow user to delete/change them, but OSO RBAC is not strong enough to do that atm.

**Comment by joshuawilson** [comment]
so who should own this?

**Comment by aslakknutsen** [comment]
@joshuawilson A Team effort? hehe

You can put it on Tenant Service.

**Comment by joshuawilson** [comment]
Closing. This is sort of fixed now that the user can't do much on their account. Also will track original and let Tenant service do the work.
