### ISSUE TITLE
Delete on Pipelines has no UI to indicate it is deleting

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1355]
_From @burrsutter on May 17, 2017 13:55_

this page https://openshift.io/rhn-engineering-bsutter/myspace/create/pipelines

the delete function
https://www.screencast.com/t/VniafQAW3Ohh

selecting delete seemingly does nothing

https://screencast.com/t/X5jikZYqm

_Copied from original issue: openshiftio/openshift.io#163_

**Comment by naina-verma** [comment]
Hi @joshuawilson ,

Do you have any update on this issue !!

**Comment by joshuawilson** [comment]
related to https://github.com/fabric8io/fabric8-ui/issues/1507 
related to https://github.com/fabric8io/fabric8-ui/issues/1344
