### ISSUE TITLE
usability issue, when logged in and visiting the openshift.io main page, where are my projects?

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1356]
_From @burrsutter on May 17, 2017 23:4_

https://screencast.com/t/mNVwutZBk

Under "Account Home", but that is not obvious

_Copied from original issue: openshiftio/openshift.io#171_

**Comment by joshuawilson** [comment]
_From @omajid on May 19, 2017 16:33_

I had the same issue. I was logged in, didn't see my projects, so I scrolled down to the bottom of https://openshift.io and clicked "Log in" again, which asked for my credentials *again* and then brought me back to https://openshift.io without showing me my projects. I thought "Account Home" was for managing my account, not to actually work on my projects.

**Comment by joshuawilson** [comment]
@catrobson can you please add this to your list of user flows that need to be reconsidered.

**Comment by omajid** [comment]
Going to https://openshift.io after logging in redirects me to my spaces correctly! Thanks for fixing this!
