### ISSUE TITLE
2 OSIO accounts, reusing github account, stuck

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1357]
_From @burrsutter on May 20, 2017 23:49_

The screen at https://openshift.io/_gettingstarted?wait=true will simply get stuck if the github account had previously been used with openshift.io.

You will see the experience about half way through this video
http://www.screencast.com/t/2N83qKcaZnR

_Copied from original issue: openshiftio/openshift.io#173_

**Comment by joshuawilson** [comment]
@alexeykazakov @dlabrecq is there something we can do to help the user when they try to do this. I know they can only link github to only one account at a time. But they don't know that.

**Comment by alexeykazakov** [comment]
Keycloak just ignores if the GitHub account had been linked to another account - https://github.com/almighty/almighty-core/issues/1291
We need to investigate why Keycloak doesn't return any error here but we will probably stop using Keycloak for storing GitHub/OSO accounts anyway.

**Comment by dlabrecq** [comment]
The UI only knows that a GitHub token is available, there is nothing to indicate where the token came from.

**Comment by joshuawilson** [comment]
Do you guys have a suggestion?

**Comment by alexeykazakov** [comment]
Options:
1. Fix Keycloak to return an error if the account is already linked. Then we can reflect it in UI.
2. Start using our own solution for linking accounts instead of KC. It will allow us to link the same GitHub account to multiple OSIO accounts.
This problem is in our TODO list. Just don't have time to fix it right now.

**Comment by joshuawilson** [comment]
@alexeykazakov do you want to duplicate this issue in the backend or track it here?

**Comment by alexeykazakov** [comment]
@joshuawilson it's already there - https://github.com/almighty/almighty-core/issues/1291

**Comment by joshuawilson** [comment]
Closing, going to track original.
