### ISSUE TITLE
Setup Wizard - Next Button goes nowehre after specifying github repo

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1360]
_From @harrymower on April 29, 2017 16:2_

![image](https://cloud.githubusercontent.com/assets/1022371/25556892/b5b9f25a-2cd3-11e7-99b7-a18b31710997.png)

_Copied from original issue: openshiftio/openshift.io#111_

**Comment by joshuawilson** [comment]
@mitchharpur please look at this.

**Comment by joshuawilson** [comment]
@corinnekrych please verify.

**Comment by corinnekrych** [comment]
has been fixed
