### ISSUE TITLE
After completing the wizard, the wizard get started menu should close and go back to the dashboard (or somewhere)

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1361]
_From @harrymower on April 29, 2017 16:6_

![image](https://cloud.githubusercontent.com/assets/1022371/25556912/3409c888-2cd4-11e7-8cf7-80309bd1089b.png)

_Copied from original issue: openshiftio/openshift.io#112_

**Comment by joshuawilson** [comment]
@catrobson Can you look at updating the flow for this?

**Comment by joshuawilson** [comment]
_From @catrobson on April 29, 2017 21:10_

Yes, it is supposed to bring you to the space dashboard after completing the QuickStart so you can see your project building.  It is also supposed to do some other things that are currently not implemented, like add your new codebase automatically.  I'll capture a workflow with all of the expected interactions when I get in front of a laptop tonight so we have that documented.  The screen flow landing on space dashboard can already be seen in the designs - https://redhat.invisionapp.com/m/share/Z9B9OWP5S#/228462993

**Comment by joshuawilson** [comment]
@mitchharpur can you take this on when @catrobson completes the designs and flow.

**Comment by joshuawilson** [comment]
_From @catrobson on April 30, 2017 3:36_

Flow:
![gettingstarted](https://cloud.githubusercontent.com/assets/3739227/25561223/e86752cc-2d34-11e7-96ed-280f0a0a9ed7.png)

**Comment by corinnekrych** [comment]
After completed Quickstart, the user is brought to space dashboard.
has been fixed.
