### ISSUE TITLE
It is possible to create a space without selecting a template

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1363]
_From @jfchevrette on May 1, 2017 13:39_

When a user creates a space, the _Template_ drop-down is empty by default. It should not be possible to create a space without a template.

The field should be marked mandatory to make sure the user selects one. We can also select a template by default.

![create-space-empty-template](https://cloud.githubusercontent.com/assets/3001/25580792/ac93a5fc-2e51-11e7-8e46-fc076868adaf.png)

_Copied from original issue: openshiftio/openshift.io#119_

**Comment by pmuir** [comment]
The template box is, by design, empty by default. Agreed it should be mandatory.

**Comment by joshuawilson** [comment]
duplicates #390 with the addition of making the field *required.
