### ISSUE TITLE
Notifications are sometimes hidden behind other overlays.

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1364]
_From @jfchevrette on May 1, 2017 13:40_

Should we make the notifications appear on top of everything else?

![error-overlay](https://cloud.githubusercontent.com/assets/3001/25580893/3a8ed994-2e52-11e7-9899-ef82e55b31d7.png)

_Copied from original issue: openshiftio/openshift.io#120_

**Comment by pmuir** [comment]
This one is bizarre - if you launch the new space dialog from the context menu (left side) the dialog is behind the notifications, if you launch it from the view, it's in front.

**Comment by joshuawilson** [comment]
@dlabrecq @mindreeper2420 can you please take a look at this. Is this still an issue?
