### ISSUE TITLE
have a richer 'Open' page for codebases/pipelines?

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1375]
I wonder if we need a nicer Open wizard that explains to users how to:

* create a workspace / open in Che
* use IDEA / Eclipse / VS Code
* install git clients and clone from the command line

So rather than having "Open in Che, Open in  IDEA, Open in Eclipse" links in various parts of the UI maybe we should just link to an Open page which lets users one click to open in Che / IDEA then when other IDEs support URLs we can open in those or provide instructions for how to import from IDEA / Eclipse / VS Code?

i.e. anywhere in the UI when we have a git URL and optionally a branch we can have an Open link/button/action that walks users through how they can work on the code in various ways (Che versus CLI versus desktop IDEs)

**Comment by joshuawilson** [comment]
@catrobson can you add this to your list of user scenarios that we need to discus / plan

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#913
