### ISSUE TITLE
HTML <Titles> should be according to the page content 

### ISSUE THREAD

**Issue by naina-verma** [fabric8-ui/fabric8-ui#1377]
HTML <Titles> should be according to the page content 
The Title Tag <title></title> should contain appropriate title with respect to page 
For example : if The page is for space dashboard , in that case the title should contain "space dashboard" keyword into it. 

This is minor enhancement in the pages

**Comment by joshuawilson** [comment]
Please be more specific. What are your referring to?

**Comment by ldimaggi** [comment]
I think that Naina is referring to the page's HTML title.

**Comment by joshuawilson** [comment]
Since each "page" is a tab in a Single Page Application there is only one <title> for the whole thing. 

We can take it as a task to see if there is some Angular trick to set the title but it works as designed.

**Comment by joshuawilson** [comment]
@kylebuch8 can you look into this and see if anything can be done?

**Comment by kylebuch8** [comment]
I have this worked out locally but I need #1585 to be finished before I can complete the task.

**Comment by rawlingsj** [comment]
> I have this worked out locally but I need #1585 to be finished before I can complete the task.

Are you sure it's not #1565?

**Comment by kylebuch8** [comment]
Ha, yes. #1565

**Comment by rawlingsj** [comment]
ah great - thanks
