### ISSUE TITLE
Help link top right should link to documentation

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ui#1378]
Help link in username dropdown should link to documentation, not Fabric8 documentation online.  Documentation link location:  https://access.redhat.com/documentation/en-us/red_hat_openshift.io/1/html-single/user_guide.

**Comment by joshuawilson** [comment]
That link returns a 404 page and after looking around I can't find the correct link there.

**Comment by joshuawilson** [comment]
@catrobson That link you provided doesn't work. Can you please provide the correct link?

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#912
