### ISSUE TITLE
the Finish button should not need to invoke Validate again if there's been no change

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1380]
if you change a field on the first page and tab, it validates. Then if I click `Finish` it validates again. It'd be nice to avoid this extra validation; as validation is kinda slow ;)

**Comment by joshuawilson** [comment]
I'm guessing this is for the App Wizard.

**Comment by jstrachan** [comment]
ah yeah sorry! :) this is the app wizard - lemme create a label for that to make it a bit more clear what issues relate to it

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#911
