### ISSUE TITLE
Routing for invalid URLs: where to go, error page?

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1384]
Atm when going to:
 
* http://localhost:3000/unkownuser/unkownspace => toaster msg to indicate 'unkown/unkown space is not known' used to fail with Exception (see PR to redirect the _home)
* http://localhost:3000/unkownuser/unkownspace/unkownroute =>error in console, validation fails without redirect.

@catrobson Should we redirect to _error page in both cases (note: those are different cases as far as angular routing is concerned but from a user point of view it might just be an invalid URL)

Attached the Error page:
![screenshot 2017-05-23 17 35 04](https://cloud.githubusercontent.com/assets/1395710/26362564/a0e7b2b8-3fde-11e7-8983-08835c0f6d54.png)

Note: links on the page does not go anywhere.

cc @joshuawilson As discussed I'm forwarding the question to Cat.

**Comment by catrobson** [comment]
@corinnekrych I think it does make sense from a user's perspective to use the 404 in these cases, and it gives them helpful links to recover from.

**Comment by joshuawilson** [comment]
@corinnekrych can we close this?

**Comment by joshuawilson** [comment]
Closed with PR #1383
