### ISSUE TITLE
community branding

### ISSUE THREAD

**Issue by rawlingsj** [fabric8-ui/fabric8-ui#1388]
we ought to have separate 'fabric8' branding that is used during the npm build of the community image for when the new console is used outside of openshift.io

FWIW fabric8 backgrounds and logos can be found here http://design.jboss.org/fabric8/

**Comment by rawlingsj** [comment]
@mindreeper2420 @catrobson @joshuawilson is this easy enough to do?  We want to include the new console in the next community release, it doesn't have to be perfect to start with but I figured we cant release it with the openshift.io branding.

**Comment by catrobson** [comment]
@rawlingsj is the same sort of header and pages used for the community build?  There is no branding other than the bar right now for the header, but we can swap out the branding on the "Account Home" page.

**Comment by rawlingsj** [comment]
@catrobson yeah I guess what I was thinking is we don't really want the text OpenShift.io appearing in the console when we run it on prem or minishift for example.

Having said that the "Account Home" is certainly the most obvious so I wonder if at build time we can use a different property that replaces the text and background with one that says fabric8 and a wallpaper / banner from http://design.jboss.org/fabric8/.  What do you think?

**Comment by catrobson** [comment]
Designs have been established in https://github.com/fabric8io/fabric8-ux/issues/456

**Comment by joshuawilson** [comment]
@catrobson if you meant to close it, please state why and go ahead and close it. Otherwise I'm assuming it was accidental.

**Comment by catrobson** [comment]
@rawlingsj do you want this issue for your work, or was this issue just to get the designs?  I'll close if only to gather design.

**Comment by joshuawilson** [comment]
I think we should leave it open to track the work. 
Now we need a way to switch between visuals. What do we use for the switch?

**Comment by catrobson** [comment]
Wouldn't this be toggled based on where the app is being launched from?   How would community users access the UI?

**Comment by joshuawilson** [comment]
fixed in #1633
