### ISSUE TITLE
Determine which pages require login

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/fabric8-ui#139]

**Comment by catrobson** [comment]
I have captured which pages require log-in on the URL spreadsheet here:  https://docs.google.com/a/redhat.com/spreadsheets/d/1cNSDuek0v1EBPpdPlFwG_Y_yOlux86m9MYf9UrF82l4/edit?usp=drive_web

**Comment by aslakknutsen** [comment]
@catrobson just as a note; GH does not require login on #5 There is a public and a private view of it. (user profile page)

**Comment by catrobson** [comment]
@aslakknutsen - Thanks for the catch!  I thought I had notated the 'view profile' page as not requiring log-in but I had that incorrect in the spreadsheet.  Updated to reflect that 'view' does not require log-in, only 'edit' profile/settings.

**Comment by joshuawilson** [comment]
Create a story for this in openshift.io repo.

**Comment by joshuawilson** [comment]
Details at #1717

**Comment by corinnekrych** [comment]
@joshuawilson is it ok to close it? should it be an epic on OSiO

**Comment by joshuawilson** [comment]
This has not been done. Why do you think it should be an epic?

**Comment by corinnekrych** [comment]
@joshuawilson is it sth to split in requirements and tasks ie: fill-in the document + implement it. or does it cover only the fill-in of the document?

**Comment by joshuawilson** [comment]
There is the list that @catrobson made. We need to review and verify that. So maybe that is enough to close this. Then we can open another issue to do the work.

An epic is larger then a user-story and I don't feel it is big enough to be an epic.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#935
