### ISSUE TITLE
App Wizard: if `KeyCloakFailureException` is returned lets display a button to link the user to the `Update Profile` page

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1405]
it seems pretty common that folks have issues with their tokens, leading the forge wizard to throw `io.fabric8.forge.generator.keycloak.KeyCloakFailureException`.

If the error includes that class of exception, it'd be good to default to showing a UI something like:

```
There was a problem using your tokens for github and OpenShift.

[Connect github and OpenShift]
```
then if users click that button it takes them to the Update Profile page. (We can always have a button to let users see the full exception if they really want to)

**Comment by joshuawilson** [comment]
@catrobson can you please look at this user flow.
@aslakknutsen @jstrachan @alexeykazakov can you confirm that the error indicates the exact issue every time and the only solution is to update the tenant? Also, what do we do when we get the tenant updating automatically and they get this error (if that is possible)?

**Comment by jstrachan** [comment]
The exception isn't related to updating the tenant at all - its when either the github or OpenShift tokens are bad.

Updating the tenant has nothing to do with tokens; that just affects what version of stuff runs in the tenant. 

Technically updating a tenant can force Jenkins to go down and restart - as can idling -  but taking down jenkins doesn't generate `KeyCloakFailureException` either. 

The `KeyCloakFailureException` indicates issues with tokens only!

**Comment by joshuawilson** [comment]
Ah, I'm sorry. I thought you wanted to update the tenant, you just wanted to bring them back to the user profile to update their token.

**Comment by jstrachan** [comment]
yeah - the most common cause of failures on the Forge wizard is github or openshift tokens are borked which then leads to the wizard failing - so this ticket is about trying to at least nudge the user to a workaround (relink github/openshift) until we figure out the real fix for tokens going bad

**Comment by corinnekrych** [comment]
@jstrachan This error could also appears when the user is not logged. Rather than forwarding to update profile, I think we should display a message to ask the user to log out / log in again.

**Comment by jstrachan** [comment]
we can easily tell if the user is logged in by checking for the presence of the KeyCloak token on the client side; if there's no KC token then redirect to login. 

However if the user is logged in then logging out and logging in again does nothing to fix broken github / OSO tokens (usually the latter TBH) - which causes the forge wizard to fail

**Comment by corinnekrych** [comment]
@jstrachan I don't understand how the update profile helps to renew/fix auth tokens

**Comment by jstrachan** [comment]
the `Update Tenant` button doesn't help at all, but there used to be a button to relink your github/openshift account on the 'Update Profile" page. Though it looks like thats now gone away! 

So I don't see how a user can ever fix their broken github/OSO tokens anyway! :) Oh dear!

I guess we could link to the KeyCloak admin page (which is a bit ninja but I don't see anything else right now in fabric8-ui) at https://sso.openshift.io/auth/realms/fabric8/account/identity

**Comment by jstrachan** [comment]
Ah I guess we can use this page now: https://openshift.io/_gettingstarted - the only problem is, if there are already 2 stale tokens linked - it redirects anyway and doesn't give the user a chance to relink.

I guess we need a 'relink tokens' page?

**Comment by corinnekrych** [comment]
mmm, as this is a temporary solution to workaround a KC issue, I'd rather not change the UI flow. Besides I found it confusing to forward the user to a new page. 
My preferred (and easy workaround) would be to provide an error message with the link to KC console https://sso.openshift.io/auth/realms/fabric8/account/identity

cc @catrobson wdyt?

**Comment by jstrachan** [comment]
I'm cool with not redirecting but providing the user with a message that their tokens are borked and what they need to do next and a link to the  page to relink the tokens etc.

Ideally we'd have a page like `_gettingstarted` we could reuse instead of moving the user to a totally different UI (the keycloak URL). I wonder if there's a way we can use `_gettingstarted` without the 'redirect to home if the user has 2 linked tokens` logic? e.g. by passing in some query argument or something?

**Comment by joshuawilson** [comment]
If fixing broken github/OSO tokens is a regular issue then maybe we should look at adding it back into the profile page. 
cc @catrobson

**Comment by jstrachan** [comment]
@joshuawilson yeah - maybe a custom Tokens tab on the profile? that looks a little like the _gettingstarted page?

**Comment by alexeykazakov** [comment]
I'm strongly against using Keycloak UI for re-linking OSO/GitHub :)
It's known issue with invalid OSO tokens and we still don't know why it's happening - https://github.com/fabric8-services/fabric8-wit/issues/1351
I don't think it's a Keycloak issue. It's rather an OSO issue. It doesn't help us though ;)
+1 to bring re-linking page back to our UI.
But what if we also create some simple endpoint which will verify the OSO/GitHub tokens by using OS/GitHub REST API behind the scenes (some simple request to OS/GitHub see if no 401/403 errors returned) which we can use in critical places in our UI and redirect to the re-linking page with proper warning message?
Something like:
GET auth.openshift.io/api/check-links 
Authentication: Bearer <access_token>

**Comment by corinnekrych** [comment]
Merging this PR: https://github.com/fabric8-ui/fabric8-ui/pull/1709 (as a first step) but leaving the issue opened as more worked is asked. 
Atm the UI catches the KeyCloakFailureException from forge backend and ask the user to unlink its account.
To be able to reproduce the issue I usually open the browser console, go to localStorage and corrupt the auth_token.
@alexeykazakov Do we know exactly how to reproduce https://github.com/fabric8-services/fabric8-wit/issues/1351 without having to tweak the UI?
@alexeykazakov do we have a ticket for backend GET auth.openshift.io/api/check-links

**Comment by alexeykazakov** [comment]
> Do we know exactly how to reproduce fabric8-services/fabric8-wit#1351 without having to tweak the UI?

No, and this is a problem.

> do we have a ticket for backend GET auth.openshift.io/api/check-links

Not yet. Feel free to create one https://github.com/fabric8-services/fabric8-auth/issues ;)

@jstrachan WDYT about such an endpoint?

> But what if we also create some simple endpoint which will verify the OSO/GitHub tokens by using OS/GitHub REST API behind the scenes (some simple request to OS/GitHub see if no 401/403 errors returned) which we can use in critical places in our UI and redirect to the re-linking page with proper warning message?
> Something like:
> GET auth.openshift.io/api/check-links
> Authentication: Bearer <access_token>

Do you see value in that?

**Comment by aslakknutsen** [comment]
Che Host/Starter, Forker and Tenant could suffer the same issue. But UI doesn't know when any of these actually required the info and what info is required. 

It would make sense if these services could return some common response that is understood by UI that there is a 'external account auth' issue if the user is around when this happen, and UI show some linking action based on that. Or some other service to call and notify about the missing auth(possible auth service?) to call when backend jobs suffer the same and the UI can react to that next time the user comes around.

**Comment by jstrachan** [comment]
Maybe the UI needs to periodically ping the tenant service to validate the GitHub & OS tokens & if they don't work unlink them so the UI knows it's time to earn the user they need to delink?

Then the forge wizard & Che operations in the UI can check the tokens are valid first before trying to talk to forge & Che?

**Comment by corinnekrych** [comment]
closing this one linked to `KeyCloakFailureException`.
