### ISSUE TITLE
Forge Quickstart : should show the jenkins 'repository' url

### ISSUE THREAD

**Issue by sbose78** [fabric8-ui/fabric8-ui#1414]
At the end of the _Add pipeline using the quickstart_ wizard,  after forge setups everything in jenkins :

Instead of showing *only* the **organization url** which currently looks like https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/sbose78

...the box should *also* show the exact **repository url** which should be something like 
https://jenkins-shbose-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/sbose78/job/anewapp/

**Comment by corinnekrych** [comment]
@sbose78 we could easily do it see:
https://github.com/fabric8-ui/fabric8-ui/compare/master...corinnekrych:wizard.display.jenkins.job.url.correctly?expand=1
BUT
then we displayed a URL which is not yet available as the jenkins job for the repo takes some time to be created. if the user hit the URL he will get a 404

I'm closing the issue, if @catrobson thinks we rather display a not yet available URL we can reopen it.
