### ISSUE TITLE
Can't remove a codebase

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1446]
_From @pkettman on June 5, 2017 14:43_

The codebases can't be removed over the OSIO GUI. When I clean them on OS over its concole, the OSIO GUI looks strange, see the picture.
![obrazek](https://cloud.githubusercontent.com/assets/26871874/26788622/235fabb8-4a0e-11e7-9a1a-9b933852477b.png)

_Copied from original issue: openshiftio/openshift.io#192_

**Comment by joshuawilson** [comment]
duplcates #552

**Comment by catrobson** [comment]
When we remove a codebase, we should also clean up/remove any workspaces in Che at the same time.

**Comment by joshuawilson** [comment]
closing to track original
