### ISSUE TITLE
Jenkins: java.lang.OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1467]
_From @burrsutter on June 7, 2017 17:16_

https://gist.github.com/burrsutter/8ec379579b07115df5e017a2a0cd45cf
workaround, restart the Jenkins pod 
oc scale dc/jenkins --replicas=0 -n burrsutter-jenkins
oc scale dc/jenkins --replicas=1 -n burrsutter-jenkins

_Copied from original issue: openshiftio/openshift.io#206_

**Comment by rawlingsj** [comment]
This has been resolved but the init tenant service doesn't have the new version yet https://github.com/fabric8io/fabric8-init-tenant/pull/104

**Comment by joshuawilson** [comment]
I think you can update the tenant now, @burrsutter can you please update your tenant and try again.

**Comment by joshuawilson** [comment]
Closing as it appears fixed.
