### ISSUE TITLE
review the Apps page UX

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1483]
we may wanna polish it a bit etc.

I like [this demo](https://drive.google.com/file/d/0B-T8vwICvu2MTDV5M25tTURoOUU/view)that Jorge pointed us at: 

<img width="1364" alt="osepipelinedashboard_export_mp4_-_google_drive" src="https://user-images.githubusercontent.com/30140/26974931-8248f864-4d15-11e7-8add-12badc4fe0ed.png">

so we could add the (optional) Promote button on the right. Then adding more detail expandable information (like features implemented, git commit, jenkins build log, view in github, CPU / memory or quotas etc)

**Comment by jstrachan** [comment]
+ @catrobson

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#904
