### ISSUE TITLE
Create Space workflow does not throw you into the new space

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1485]
_From @burrsutter on June 9, 2017 14:44_

Video
https://screencast.com/t/1q2lHgdfl

By default, it left me in my old space.  Granted, I canceled out of the Add to Space wizard but that should still have put me into the new added space

_Copied from original issue: openshiftio/openshift.io#213_

**Comment by joshuawilson** [comment]
@fabric8io/uxd @catrobson what should the work flow be here. Currently, when you finish the wizard it changes to the the space you created. What should happen when you cancel?

**Comment by Essjaysee** [comment]
@joshuawilson If you're on the first screen when you're naming it and selecting the method: https://redhat.invisionapp.com/share/ZQARDX35J#/221494634_Create_Space_Modal

If you're on the wizard itself: https://redhat.invisionapp.com/share/ZQARDX35J#/222201994_Wizard_-_Select_Stack_ALT_Empty

Hope that helps!

**Comment by joshuawilson** [comment]
Thanks @Essjaysee according to the designs we should get redirected to the newly created space when you cancel.
