### ISSUE TITLE
Plan out my space appears to be a dead button

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1486]
_From @burrsutter on June 9, 2017 14:45_

And since it is first in the list, that is going to be very confusing to the new end-user 
https://screencast.com/t/3B8NL94gq

_Copied from original issue: openshiftio/openshift.io#214_

**Comment by corinnekrych** [comment]
closing as we fixed it with displaying only 2 buttons: import from repo and quickstart.
