### ISSUE TITLE
Unable to "create Workspace"  504 gateway timeout 

### ISSUE THREAD

**Issue by naina-verma** [fabric8-ui/fabric8-ui#1496]
Unable to "create Workspace"  504 gateway timeout 
Video link 
https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COYTg5QkFDa3VDaGc/view?usp=sharing

**Comment by joshuawilson** [comment]
Are you still having this issue?

**Comment by naina-verma** [comment]
yes @joshuawilson

**Comment by joshuawilson** [comment]
@naina-verma I'm unable to play the video. Additionally the video is not public and this is a public repo.

It would be better if you wrote out the steps to reproduce it.

**Comment by naina-verma** [comment]
https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COYTg5QkFDa3VDaGc/view?usp=sharing

**Comment by naina-verma** [comment]
@joshuawilson https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COYTg5QkFDa3VDaGc/view?usp=sharing

**Comment by joshuawilson** [comment]
@naina-verma if I have to be logged in via my red hat account to see it, it is not public. Please just list the steps to reproduce this issue. That will make it easier to search this issues too.
