### ISSUE TITLE
Intermittent issue - Create workspace failing on openshift.io - 504 error reported

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1515]
Started seeing this on June 14 - in a new space, with a new (quickstart) project - attempting to create a new workspace is failing. No error is reported to the user in the UI. 

No 'Access-Control-Allow-Origin' header is present on the requested resource.

This error is logged in the Chrome console:

``
2api.openshift.io/api/codebases/cff4a44a-67e1-4a8d-a67e-d2dcc90354d3/create:1 POST https://api.openshift.io/api/codebases/cff4a44a-67e1-4a8d-a67e-d2dcc90354d3/create 504 (Gateway Time-out)
almusertest1/june14/create:1 XMLHttpRequest cannot load https://api.openshift.io/api/codebases/cff4a44a-67e1-4a8d-a67e-d2dcc90354d3/create. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.
main.82f67a8….bundle.js:1 Response {_body: ProgressEvent, status: 0, ok: false, statusText: "", headers: Headers…}
``

**Comment by jstrachan** [comment]
this looks like an issue with being able to create a Codebase which is a WIT thing rather than forge/jenkins

**Comment by ldimaggi** [comment]
This is still a problem as of June 22 - see screencast here: 
https://drive.google.com/open?id=0B1s-ZoxD8FjUR0xUR3MyQU45Zjg

**Comment by jstrachan** [comment]
I don't understand those 3 videos; they don't seem to match this issue. The first one shows some JavaScript console log before the wizard is invoked (maybe when Forge was down, not sure - can't quite see on the screen - doesn't look like the failure to create a Codebase error at least). The second video shows a working wizard. The third the codebase page?

**Comment by ldimaggi** [comment]
Yes - but on the 3rd video:

* The "Create Codebase" link is missing
* Clicking on "Create Codebase" in the kebab results in the 504 error

Are not able to recreate this error at https://openshift.io?

Thx!

**Comment by ldimaggi** [comment]
Is this problem unique to the user account - that we are using for tests?

**Comment by ldimaggi** [comment]
In looking at Che - it looks like the workspaces ARE being created - the workspace creation takes several minutes - and the workspaces fail to start due to deployment errors:

![screenshot from 2017-06-22 10-56-17](https://user-images.githubusercontent.com/642621/27442554-8d81eb86-573e-11e7-9abf-037d0bd58215.png)


![screenshot 18](https://user-images.githubusercontent.com/642621/27442560-93da631e-573e-11e7-9339-e0e82cf6860e.png)


![screenshot 19](https://user-images.githubusercontent.com/642621/27442571-9b02ef26-573e-11e7-8633-4978a1923f5a.png)

**Comment by joshuawilson** [comment]
@ldimaggi are you able to reproduce this?

**Comment by ldimaggi** [comment]
Closing as not reproducible.
