### ISSUE TITLE
Getting started does not work with Safari

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1516]
_From @hferentschik on June 13, 2017 21:19_

I tried to launch OpenShift.io from Safari and followed the sign up process and the linking of the required accounts. I ended up on the page with the "Get Started" link:

![getting-started](https://user-images.githubusercontent.com/296354/27105068-7cf8a98c-508e-11e7-9f14-dabcd537bf8e.png)

Once I press the button, the following page stays empty:

![empty](https://user-images.githubusercontent.com/296354/27105086-8bb486f8-508e-11e7-999a-1e782d06e22c.png)

Took me a while to figure out that this is a browser thing. Doing the same in Firefox got me to the OpenShift.io homepage. 

Is Safari not supported? And if not, should I not be notified? 

_Copied from original issue: openshiftio/openshift.io#229_

**Comment by joshuawilson** [comment]
Currently we are only testing against Chrome. We plan to support the other browsers moving forward.

**Comment by joshuawilson** [comment]
@dlabrecq @mindreeper2420 can you please take a look at running on Safari.

**Comment by mindreeper2420** [comment]
@joshuawilson @dlabrecq I can log into the system without error on Safari.

**Comment by dlabrecq** [comment]
I could not reproduce this on Safari 10.1.1. Tested both prod and prod-preview. Overall, the site looks pretty good on Safari.

The only time I ever saw a blank screen was when I inadvertently logged out. And that was only because I manually removed my OpenShift token during testing.

**Comment by joshuawilson** [comment]
@hferentschik can you please verify. You may want to try a hard refresh too. cmd+shift+r

**Comment by hferentschik** [comment]
I tried with cdm+shift+r, no luck. 

Using the developer tools, I can see several Javascript errors. The first one indicating that there is an error retrieving my spaces (which would explain why all is blank):

    2406396Failed to retrieve list of spaces owned by user
    error — main.8cc8a658619e8f07113f.bundle.js:1:2406396
    initSpaces — 2.6c302b6ab2054293e2b4.chunk.js:1
    (anonymous function) — 2.6c302b6ab2054293e2b4.chunk.js:1
    __tryOrSetError — vendor.73b76953eab25ca018c6.bundle.js:1:196763
    next — vendor.73b76953eab25ca018c6.bundle.js:1:195881
    _next — vendor.73b76953eab25ca018c6.bundle.js:1:194936
    next — vendor.73b76953eab25ca018c6.bundle.js:1:194572
    _subscribe — vendor.73b76953eab25ca018c6.bundle.js:1:411042
    _trySubscribe — vendor.73b76953eab25ca018c6.bundle.js:1:149146
    subscribe — vendor.73b76953eab25ca018c6.bundle.js:1:148969
    _trySubscribe — vendor.73b76953eab25ca018c6.bundle.js:1:149146
    subscribe — vendor.73b76953eab25ca018c6.bundle.js:1:148969
    ngOnInit — 2.6c302b6ab2054293e2b4.chunk.js:1
    checkAndUpdateDirectiveInline — vendor.73b76953eab25ca018c6.bundle.js:1:30484
    checkAndUpdateNodeInline — vendor.73b76953eab25ca018c6.bundle.js:1:46978
    prodCheckAndUpdateNode — vendor.73b76953eab25ca018c6.bundle.js:1:52237
    (anonymous function) — HomeComponent_Host.ngfactory.js:21
    checkAndUpdateView — vendor.73b76953eab25ca018c6.bundle.js:1:46185
    callViewAction — vendor.73b76953eab25ca018c6.bundle.js:1:49695
    execEmbeddedViewsAction — vendor.73b76953eab25ca018c6.bundle.js:1:49458
    checkAndUpdateView — vendor.73b76953eab25ca018c6.bundle.js:1:46214
    callViewAction — vendor.73b76953eab25ca018c6.bundle.js:1:49695
    execComponentViewsAction — vendor.73b76953eab25ca018c6.bundle.js:1:49140
    checkAndUpdateView — vendor.73b76953eab25ca018c6.bundle.js:1:46389
    detectChanges — vendor.73b76953eab25ca018c6.bundle.js:1:137245
    forEach
    tick — vendor.73b76953eab25ca018c6.bundle.js:1:102481
    (anonymous function) — vendor.73b76953eab25ca018c6.bundle.js:1:100256
    onInvoke — vendor.73b76953eab25ca018c6.bundle.js:1:93242
    run — polyfills.f49acb8aeb061f0c40eb.bundle.js:1
    next — vendor.73b76953eab25ca018c6.bundle.js:1:100238
    (anonymous function) — vendor.73b76953eab25ca018c6.bundle.js:1:89946
    __tryOrUnsub — vendor.73b76953eab25ca018c6.bundle.js:1:196640
    next — vendor.73b76953eab25ca018c6.bundle.js:1:195935
    _next — vendor.73b76953eab25ca018c6.bundle.js:1:194936
    next — vendor.73b76953eab25ca018c6.bundle.js:1:194572
    next — vendor.73b76953eab25ca018c6.bundle.js:1:281112
    emit — vendor.73b76953eab25ca018c6.bundle.js:1:89709
    checkStable — vendor.73b76953eab25ca018c6.bundle.js:1:92770
    setHasMicrotask — vendor.73b76953eab25ca018c6.bundle.js:1:93798
    onHasTask — vendor.73b76953eab25ca018c6.bundle.js:1:93366
    hasTask — polyfills.f49acb8aeb061f0c40eb.bundle.js:1
    _updateTaskCount — polyfills.f49acb8aeb061f0c40eb.bundle.js:1
    _updateTaskCount — polyfills.f49acb8aeb061f0c40eb.bundle.js:1
    runTask — polyfills.f49acb8aeb061f0c40eb.bundle.js:1
    drainMicroTaskQueue — polyfills.f49acb8aeb061f0c40eb.bundle.js:1
    promiseReactionJob
    
For that it's worth, I am using a older version of Safari atm - 10.0.2

**Comment by joshuawilson** [comment]
We do not support Safari 10.0.2. Please update to 10.1.1. 
Closing, will not fix.

**Comment by hferentschik** [comment]
> We do not support Safari 10.0.2. Please update to 10.1.1.

Wau :-(. Do the required APIs change so dramatically?

**Comment by joshuawilson** [comment]
@dgutride @mindreeper2420 can you please comment on @hferentschik question.

**Comment by dlabrecq** [comment]
Without installing an older version of Safari, I don't know what the underlying problem is? However, if there are JavaScript errors, that would prevent the home page from rendering.

**Comment by dgutride** [comment]
@hferentschik - we saw this locally when testing - this seems to be a bug in Safari missing support for the Headers browser API which Angular 4 depends on.  They fixed it in the next release (searching for safari 10 headers polyfill reveals a number of other frameworks also hit this same problem including Polymer).

**Comment by hferentschik** [comment]
@dgutride thanks for the explanation. Much appreciated. I am wondering though whether there should not be browser version checks which would help the user to trouble shoot the error. I am basically not so much behind in terms of versions. I would assume other people hit the same problem. It would be nice to get at least some sort of feedback that my browser in this version is not supported.

**Comment by joshuawilson** [comment]
@hferentschik we are putting together a matrix of supported browsers and figure we can add it to the wiki. That way anyone can see what version of their preferred browser they need.
