### ISSUE TITLE
[Bug]Build failed with "java.io.FileNotFoundException: /root/.mvnrepository/io/vertx/vertx-health-check/3.4.1/vertx-health-check-3.4.1.pom.part.lock "

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1525]
_From @naina-verma on June 15, 2017 12:9_

Build failed with "Caused by: java.io.FileNotFoundException: /root/.mvnrepository/io/vertx/vertx-health-check/3.4.1/vertx-health-check-3.4.1.pom.part.lock "

Steps to reproduce 
- Create a space
- Add to space 
- chose Basic vertx 
This build fails due to error !
logs : https://gist.github.com/almightytest/2eeecafe969b165a6997f16fb59f440a

_Copied from original issue: openshiftio/openshift.io#233_

**Comment by jstrachan** [comment]
wonder if this is basically the same as this one that the test account ran out of PV space preventing any new writes? https://github.com/fabric8io/fabric8-ui/issues/1526

**Comment by joshuawilson** [comment]
@naina-verma can you please confirm.

**Comment by joshuawilson** [comment]
Closing as this appears to be a duplicate.
