### ISSUE TITLE
We should be able to stop and delete a workspace from the codebase UI

### ISSUE THREAD

**Issue by l0rd** [fabric8-ui/fabric8-ui#1528]
Users are not able to clean-up workspaces right now and look for workarounds like using [Che dashboard](https://github.com/redhat-developer/rh-che/issues/105).

Some discussions about porting Che dashboard functionalities to the codebase UI have already been initiated. But having stop and delete buttons is really the minimum otherwise we won't be able to remove Che dashboard.

cc @ashumilova @gorkem @ibuziuk @joshuawilson

**Comment by joshuawilson** [comment]
I'm still not sure how much functionality makes sense to add to the codebases page. That said, we should discuss it here.

cc @maxandersen @aslakknutsen @catrobson

**Comment by joshuawilson** [comment]
The status/open-for-dev label is for issues that have a clear specification. This one needs discussion.

**Comment by joshuawilson** [comment]
@catrobson we are going to need to work with @l0rd and the che team to figure out how we either change the Codebases page or what a Workspaces page would look like so that we can provide the che controls that are needed.

**Comment by slemeur** [comment]
I worked on the following set of specifications for these use cases: 
https://redhat.invisionapp.com/share/94CH0VNV5

I think it covers what is needed, but we can refined them and scope them. First goal would be to only allow browsing the existing workspaces and deleting them from a new "Workspaces" tab. We can then add the other capabilities.

**Comment by joshuawilson** [comment]
The visuals you provided appear releated to https://github.com/fabric8-ui/fabric8-ui/issues/1825

**Comment by slemeur** [comment]
@joshuawilson: They are also providing mockups for what a "Workspaces page" would look like.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#896
