### ISSUE TITLE
Add Less Linter to Build Process

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ui#1530]
In order to ensure the the HTML/CSS meets the code guidelines as defined in the [Code Guidelines](https://github.com/fabric8io/fabric8-ux/blob/master/code-guidelines.md) document, a Linter needs to be added to the build process that will fail the build when deviations are made.

**Requires the following work to be completed:**
- PR #1419

**Verification Conditions:**
- All LESS files follow the guidelines, as governed by [code-guidelines.md](https://github.com/fabric8io/fabric8-ux/blob/master/code-guidelines.md)

**Additional:**
- share configuration and results with other fabric8io repos

**Comment by mindreeper2420** [comment]
@joshuawilson I looked at [lesslint](https://github.com/lesshint/lesshint) and was able to get something working, but nothing more than a print-out of the errors. I have a config file (.lesshintrc), if you'd like to take a look at it.

**Comment by joshuawilson** [comment]
Thanks, I'll take a look at the tool.

**Comment by mindreeper2420** [comment]
Closed as part of PR https://github.com/fabric8-ui/fabric8-ui/pull/1935
