### ISSUE TITLE
Intermittent error - codebase not created when a new project is created

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1552]
Steps to recreate:
* Create a new space
* Add to space - via Quickstart wizard - Vert.X project
* Observe that sometimes - (10%?) of the time - the codebase is not created - no error is logged to the UI or to the Chrome console

Assigning to ldimaggi to investigate - is anyone else seeing this?

**Comment by joshuawilson** [comment]
Can you confirm that the codebase does NOT get created in github, not just on the codebases page?

**Comment by ldimaggi** [comment]
Thanks for the reminder - the github repo is created.

**Comment by joshuawilson** [comment]
@corinnekrych I think this is an issue in the app-wizard

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#894
