### ISSUE TITLE
Cannot deselect checkbox options in QuickStart Wizard Step 4

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1556]
_From @mishaone on June 21, 2017 5:16_

Step 4/5 in the Quickstart wizard offers two checkboxes for a Jenkins build and triggering build. Neither can be deselected. Deselecting either or both of these results in OSIO verifying and then re-selects both. Not sure why this is an option to change if it can't actually be changed.

![checkboxes](https://user-images.githubusercontent.com/926572/27368011-7453d3b4-5693-11e7-9656-14012d9b9ad9.png)

Additionally, both steps 4 and 5 are titled Build Configuration and appear to be the same.

_Copied from original issue: openshiftio/openshift.io#264_

**Comment by corinnekrych** [comment]
This issue is not reproducible. it has been fixed.
