### ISSUE TITLE
add community branding and a flag to turn it on

### ISSUE THREAD

**Issue by rawlingsj** [fabric8-ui/fabric8-ui#1565]
We have the community branding from UX https://github.com/fabric8io/fabric8-ux/issues/456#issuecomment-307533039 what we need next is to include this in the fabric8-ui along with a flag (disabled by default) that we can enable in the community fabric8-ui openshift / kubernetes YAML.

I can have a crack at this if someone can point me in the right direction or please assign to someone that can do it.

**Comment by joshuawilson** [comment]
Where would you think the should go or get set? We have some env vars that might work.

**Comment by rawlingsj** [comment]
I'm not familiar with the fabric8-u code or how assets are added but I was thinking we have an env var `BRANDING` and a couple of constants in the code `OSIO` and `FABRIC8` which we use to switch between the two.  
Then in the community [DeploymentConfig.yml](https://github.com/fabric8io/fabric8-platform/blob/master/apps/fabric8/src/main/fabric8/deployment.yml#L24) we set the `BRANDING=FABRIC8` env var .  Where in the code does the current OpenShift.io users home page branding get added?

**Comment by rawlingsj** [comment]
@joshuawilson @mindreeper2420 is this something that's in my novice ability or should someone else look at it?

**Comment by joshuawilson** [comment]
@rawlingsj this is more intermediate level. We are focused on Blocking and P1 issues that need to be done for the release.

**Comment by rawlingsj** [comment]
Ok fair enough but just so you know the fabric8 community project is now released and folks have started installing it. The first thing they see is openshift.io product branding rather than community which isn't great.

**Comment by joshuawilson** [comment]
related to #1388

**Comment by joshuawilson** [comment]
fixed in #1633
