### ISSUE TITLE
Refreshing the browser from the pipelines history page hangs the browser

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1568]
To recreate this bug:
* Navigate to the pipelines page - for example - https://openshift.io/ldimaggi%40redhat.com/june17/create/pipelines
* Refresh the browser - press control/R

(Confirmed this with Chrome on Windows10 and RHEL7)

**Comment by joshuawilson** [comment]
Can you please try again and confirm. There have been several updates and it works for me.

**Comment by ldimaggi** [comment]
Still hangs for me.

**Comment by joshuawilson** [comment]
I still haven't seen this. @ldimaggi please confirm.
@dgutride can you try this and confirm.

**Comment by ldimaggi** [comment]
The issue is no longer being seen. Closing.
