### ISSUE TITLE
Feature flag/toggles

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ui#1576]
A user can turn on or off the ability to see experimental features in OSIO.

Stage 1:
 Experimental features on/off

Stage 2: 
 Allow user to turn on or off certain experimental features

**Comment by catrobson** [comment]
https://martinfowler.com/articles/feature-toggles.html

**Comment by joshuawilson** [comment]
We have an Epic for this at https://github.com/openshiftio/openshift.io/issues/278

**Comment by catrobson** [comment]
Initial work happening in this fabric8-ux story:  https://github.com/fabric8-ui/fabric8-ux/issues/510  

You can see user flows and some design ideas forming here:  https://redhat.invisionapp.com/share/WJCDBEBYM

**Comment by catrobson** [comment]
@joshuawilson - main question I have for Dev team - if you look at user flows I have a Phase 1, 2, 3.  Do those phases make sense to you?  Are Phase 1 and 2 useful distinctions especially to get this done in a more timely fashion?  Reviewed with @qodfathr and he was happy with the direction of these user flows.  Designs still need more work.

**Comment by joshuawilson** [comment]
@catrobson the designs look like what I thought it should be. How would the Phases work?
Long term we may want to be more specific and have a whole page in the profile to check off the areas that you want enable and maybe the features/phases for them.

**Comment by catrobson** [comment]
Stage 1 has been completed.  Will create stories for stage 2 separately.
