### ISSUE TITLE
Configure CI/CD for the whole UI

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1591]
Currently the UI repos build independently but they need to role up into the components that use them.

Additionally we need to have every push to master update prod automatically for CD.

**Comment by joshuawilson** [comment]
@jstrachan were you ever able to build the thing that would do this?

**Comment by jstrachan** [comment]
its on my TODO list once I've finished a few other things... hopefully I'll get to it soon

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#888
