### ISSUE TITLE
Build configuration appears twice in Create a new Starter project wizard

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1593]
_From @ppalaga on June 23, 2017 8:25_

Create a new Starter  project
EXPECTED: Build configuration step appears just once
ACTUAL: Build configuration step appears twice
![image](https://user-images.githubusercontent.com/1826249/27473116-48f39170-57fe-11e7-84ed-5fc68ee99b04.png)

_Copied from original issue: openshiftio/openshift.io#280_

**Comment by joshuawilson** [comment]
@ppalaga this is a limitation of the Forge backend that requires a validation step. That said, we are aware of it and are looking for a better way to handle it.

**Comment by corinnekrych** [comment]
This is a Fabric8-generator forge Addon issue. The duplicate step is returned by Forge backend.

**Comment by corinnekrych** [comment]
merged and fixed in forge addon
