### ISSUE TITLE
For newly provisioned OSIO users, Jenkins and/or Che projects are not immediately visible in OpenShift (reproducible)

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1606]
Related to: https://github.com/fabric8io/fabric8-ui/issues/1598

The new account that was provisioned was not provided with a Che project:

 token provided.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * osiotest314
    osiotest314-jenkins
    osiotest314-run
    osiotest314-stage

Using project "osiotest314".
$ oc get projects
NAME                  DISPLAY NAME   STATUS
osiotest314                          Active
osiotest314-jenkins                  Active
osiotest314-run                      Active
osiotest314-stage                    Active

![screenshot from 2017-06-27 13-11-17](https://user-images.githubusercontent.com/642621/27600580-7299fe30-5b3a-11e7-84bc-3165ee332368.png)

**Comment by joshuawilson** [comment]
@rawlingsj @aslakknutsen @jstrachan can you please take a look at this.

**Comment by jstrachan** [comment]
There's was an issue with the Che YAML - the new release fixing it should be out shortly - try update tenant

**Comment by ldimaggi** [comment]
The Update tenant button does not respond for the test user account for which a Che project was not created when the account was provisioned.

(does not respond = does not highlight, does not respond visually, and nothing in the Chrome browser console log )

**Comment by ldimaggi** [comment]
OK - that did work - the user account looks to be correct now - verifying.

**Comment by ldimaggi** [comment]
The problem seems to be fixed now - but - will leave this issue open until we can verify that the problem is not recreated for other/all new user accounts.

**Comment by ldimaggi** [comment]
After retrying this test with a second (totally new) user account ("osiotest3142"), the pattern seems to be consistent:
* Create a new user, register the user
* After the user's first login to OSIO, the Che and/or Jenkins projects are not visible in the OpenShift web console - also the projects are not listed in output from oc CLI.
* The projects appear after the user updates the tenant service from their profile (in OSIO). 
* The missing services, once they are appear in the OpenShift web console, show the same creating time as the other services - which indicates that the services were actually created during the user's initial login, but are not visible - for what reason?

After login:

![screenshot from 2017-06-28 13-18-46](https://user-images.githubusercontent.com/642621/27656069-b0b33f0c-5c15-11e7-8316-942d1b8522c0.png)


After update of the tenant service:

![screenshot from 2017-06-28 15-21-35](https://user-images.githubusercontent.com/642621/27656089-c0bd5c34-5c15-11e7-9ec1-1432ec80c386.png)

**Comment by jstrachan** [comment]
this sounds like an issue with fabric8-init-tenant or WIT - I raised this https://github.com/fabric8io/fabric8-init-tenant/issues/122

**Comment by aslakknutsen** [comment]
It's getting Forbidden from OSO applying the view/edit roles in the Jenkins namespace which skips the Che creation.. Looks like some async issue. Investigating.

**Comment by ldimaggi** [comment]
https://github.com/fabric8io/fabric8-init-tenant/issues/122

**Comment by aslakknutsen** [comment]
Fixed by https://github.com/fabric8io/fabric8-init-tenant/pull/144
