### ISSUE TITLE
Add to Space -> Import Code -> "OK" button displayed after import is non-operational

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1607]
![screenshot from 2017-06-27 15-00-34](https://user-images.githubusercontent.com/642621/27605180-da059106-5b49-11e7-97b9-094d0cdd0289.png)

**Comment by corinnekrych** [comment]
this one is fixed by https://github.com/fabric8-ui/fabric8-ui/issues/1613
