### ISSUE TITLE
Areas to use tree-list view

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ui#1617]
Change over Area list page to use tree-list view control to show parent and children areas as a tree rather than in a flat list with parent/child/grandchild/etc.

**Comment by joshuawilson** [comment]
@catrobson is this to be designed or do you have designs?

**Comment by joshuawilson** [comment]
ping @catrobson

**Comment by catrobson** [comment]
Dana and I discussed that this could move forward without designs for just swapping out the list component itself to a tree-list component.  None of the other interactions will be affected, and the only change we discussed was that we would consider adding in drag-and-drop with the tree-list component.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#885
