### ISSUE TITLE
UX for Remote work items

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1621]
_From @Mgranfie on October 12, 2016 15:18_

As a user I should be able to use the ALM tools to work with issues that currently exist in other tools such as GIT, Bugzilla etc, without having to recreate them in Almighty.
- User should be able to directly interact with attributes from the remote issue, as a work item in ALM.
- User should not have to update the remote issue, or refresh the Almighty to see updates made on an remote issue, in the external system.
- Would changes to the WI in Almighty automatically be updated on the remote issue in the external system?
- If the WI is removed from Almighty, it will still exist in the external system.
- Changes to the issue in the external system, should eventually be reflected on the WI in Almighty.
- A user should be able to identify an remote WI from a normal WI.
- A user should be able to identify what system the remote WI lives in.
- Should the user be able to access the external system for the issue, directly, from within Almighty ?
- The user experience should be a seamless experience for the end user.

_Copied from original issue: fabric8-services/fabric8-wit#356_

**Comment by joshuawilson** [comment]
_From @maxandersen on October 13, 2016 11:9_

You are using both remote and external interchangeably in this story.  I think it is important we do not mix up those two related but quite different from user perspective.

All remote issues are external by definition, but you could see at some point that not all external issues are remote issues. I've updated the text to reflect that.

p.s. the system is called Almighty, not ALM :)

**Comment by joshuawilson** [comment]
_From @maxandersen on October 13, 2016 11:14_

I also updated the changes in the external system should immediately take effect in Almighty to say eventually. It is too much to expect remote items that might only be possible to fetch with coarse grained intervals to be updated immediately.

**Comment by joshuawilson** [comment]
_From @ldimaggi on October 13, 2016 17:31_

Have we thought about how/where we will configure the remote system fetch/refresh time intervals? (Something similar to email/calendar refresh on a phone/tablet? Will we also include a "manual fetch" option?)

**Comment by catrobson** [comment]
Closing as any work around remote work items will be captured and handled in fabric8-planner.
