### ISSUE TITLE
Not reproducible - user accounts can be rendered unusable - "Already created BuildConfig" cited in logs - no build configs found

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1625]
This test - https://ci.centos.org/job/devtools-test-end-to-end/ - started failing on Sunday, July 2. The error logged (Jenkins log) is:

```
INFO: OpenShift OAuth: user almusertest1, stored in the matrix as almusertest1-edit, 
based on OpenShift roles [view, edit] already exists in Jenkins
```
However, no build configs are found in the OpenShift Jenkins project:
![screenshot from 2017-07-03 16-29-47](https://user-images.githubusercontent.com/642621/27807203-40bec2ec-600d-11e7-9c83-6ec98a044dfd.png)

The error displayed to the user is:
```
ExecuteForgeCommandError
The forge-quick-start :: execute :: 1 command failed or only partially succeeded
name = ForgeApiServerError origin = Fabric8ForgeService message = An unexpected server side forge api error occurred 
inner = httpError = status = 500 statusText = Internal Server Error url = https://forge.api.openshift.io/forge/commands/fabric8-new-project/execute body = 

results = [ { status = SUCCESS } , { message = Added Jenkinsfile to project status = SUCCESS } , {
message = Created git repository: https://github.com/almightytest/july3ab status = SUCCESS } , { message = Failed to create Jenkins Organisation job:: java.lang.IllegalStateException: Failed to create the GitHub Org Job at https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest. javax.ws.rs.WebApplicationException: Failed to process https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/createItem?name=almightytest and got status: 400 Bad Request status = FAILED } , { message = Already created BuildConfig almusertest1/july3ab status = SUCCESS } ]
```
[Jenkinslog.txt](https://github.com/fabric8-ui/fabric8-ui/files/1120518/Jenkinslog.txt)

**Comment by ldimaggi** [comment]
Deleting builk configs, deployment configs, restarting pods, etc. has no effect on this bug.

**Comment by ldimaggi** [comment]
After the jenkins project's pods are scaled to zero, persistent volume claims remain:
```
oc get pods
No resources found.

oc describe quota
Name:		compute-resources
Namespace:	almusertest1-jenkins
Scopes:		NotTerminating
 * Matches all pods that do not have an active deadline.
Resource	Used	Hard
--------	----	----
limits.cpu	0	4
limits.memory	0	2Gi


Name:		compute-resources-timebound
Namespace:	almusertest1-jenkins
Scopes:		Terminating
 * Matches all pods that have an active deadline.
Resource	Used	Hard
--------	----	----
limits.cpu	0	4
limits.memory	0	2Gi


Name:			object-counts
Namespace:		almusertest1-jenkins
Resource		Used	Hard
--------		----	----
persistentvolumeclaims	3	3
replicationcontrollers	8	20
secrets			22	40
services		4	5
```

**Comment by ldimaggi** [comment]
At this point - how can a user clear these persistent volume claims?

**Comment by joshuawilson** [comment]
@jstrachan can you answer this one?

**Comment by ldimaggi** [comment]
The error message is generated here:
https://github.com/fabric8io/fabric8-generator/blob/master/src/main/java/io/fabric8/forge/generator/kubernetes/CreateBuildConfigStep.java#L236

But - what is causing this? And why only for this account? Thx!

**Comment by jstrachan** [comment]
BuildConfigs are in the users namespace `almusertest1`; not in the `almusertest1-jenkins` namespace. The Builds for the pipelines are there too. There are temporary S2I Builds created in the `almusertest1-jenkins` namespace but like all Builds they are transient and OpenShift will GC them at some point.

Then main thing to check on is `BuildConfig` resources in `almusertest1` - they should be created by the Forge wizard and not GCd

**Comment by ldimaggi** [comment]
Was just able to recreate this error with a new user account - steps to reproduce:
* Create 4 new projects (Vert.X quickstart) in a new space with a new user account

As expected, the 4 projects/apps result in quotas being reached for stage and run:
```
Resource	Used	Hard
--------	----	----
limits.cpu	2	2
limits.memory	1Gi	1Gi
```

Adding a 5th project resulted in the "Already created BuildConfig"  error. But - this scenario was not reproducible.

oc get bc -n osiotest314-jenkins
NAME         TYPE      FROM      LATEST
july6-s2i    Source    Binary    5
july6a-s2i   Source    Binary    4
july6b-s2i   Source    Binary    3
july6c-s2i   Source    Binary    2
july6d-s2i   Source    Binary    1

**Comment by rawlingsj** [comment]
> oc get bc -n osiotest314-jenkins
NAME TYPE FROM LATEST
july6-s2i Source Binary 5
july6a-s2i Source Binary 4
july6b-s2i Source Binary 3
july6c-s2i Source Binary 2
july6d-s2i Source Binary 1

Are you sure you've given the correct command and information above?  I wouldn't expect any build configs in the osiotest314-jenkins namespace especially with 'Source Binary' in the description.  The list you've given above are completed s2i builds in the jenkins namespace.  

Builds != BuildConfigs

In fact I've just read @jstrachan comment above https://github.com/fabric8-ui/fabric8-ui/issues/1625#issuecomment-313393753 and he has described it exactly.  The thing to check is the build configs in the users home namespace, i.e.
```
oc get bc -n osiotest314
```

**Comment by joshuawilson** [comment]
@ldimaggi were you able to do as they said? and did it fix things?

**Comment by ldimaggi** [comment]
I think that we can close this issue - that account was put into a bad state - other related, and more specific issues, have been logged since then. Thx!
