### ISSUE TITLE
Duplicated "Create new space" header

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1627]
_From @bartoszmajsak on June 29, 2017 7:56_

When creating new space from the **Profile**, modal has double "Create new space" label.

![image](https://user-images.githubusercontent.com/719616/27677169-081e8bde-5cb1-11e7-968c-79635be273a8.png)

It seems that first one is part of `<h4 class="modal-title">Create new space</h4>` and the other is nested in `<space-creator>`.

Chrome v59.0.3071.104 

_Copied from original issue: openshiftio/openshift.io#301_

**Comment by joshuawilson** [comment]
@mindreeper2420 this is only from the **Profile** page.

**Comment by mindreeper2420** [comment]
As the Space Creator component contains the title, it does not need to be passed by the page to the modal itself. Removing the title from the `<modal #createSpace` call eliminates the duplicate title.
