### ISSUE TITLE
"My work items" in dashboard rendering badly

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1630]
_From @mishaone on July 4, 2017 23:52_

Right after logging in, we're take to the dashboard with Recent Spaces, My work Items and recent active pipelines. The "My work items" part of this is rendering oddly. The first screenshot shows how the title of the work items seems to be overwriting a hash. The second shows multiple work items doing the same. I highlighted the title to see what exactly it said.

![workitemerror](https://user-images.githubusercontent.com/926572/27844640-8f28b842-6167-11e7-91e8-235f4dabe745.png)

![workitemsrendering](https://user-images.githubusercontent.com/926572/27844644-94f647d0-6167-11e7-9ff7-c36a79de6bbb.png)

_Copied from original issue: openshiftio/openshift.io#315_

**Comment by mindreeper2420** [comment]
@joshuawilson it looks like something is going on with the retrieval of the work item id - when I go into the Planner, the Work Item ID is a 36 character code.

**Comment by michaelkleinhenz** [comment]
This is due to the change of the id handling. The id field now holds a UUID and the UI should use the new system.number field for local ID display. This has to be adapted throughout OSIO. In Planner, it is already fixed, but is stuck in deploy hell. As soon as we get the pipeline fixed, this will be fixed on Planner. On Platform, the same needs to be done.

**Comment by mindreeper2420** [comment]
@joshuawilson @michaelkleinhenz - I changed the string to be `{{workItem.attributes['system.number']}}` and it is pulling the proper number now, based on the context of the Space. It now shows the first work item in Space 'adam' as '1' and the first work item in Space 'miranda' and '1'. No longer does it jump from '1' to '12' when there are only two numbers in the Space.
