### ISSUE TITLE
Project creation ("add to space") dialog's "OK button is non-functioning

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1640]
First started seeing this issue on July 6 - after creating a new project - the "OK" button in the dialog is non-functioning - no error is displayed for the user or written to the Chrome browser console log:

![screenshot from 2017-07-06 09-16-55](https://user-images.githubusercontent.com/642621/27913025-c4a591d2-622c-11e7-83c3-dbfbbfc067cf.png)

**Comment by corinnekrych** [comment]
@ldimaggi it should be fixed by https://github.com/fabric8-ui/fabric8-ui/pull/1638
