### ISSUE TITLE
Project creation ("add to space") - fails to create codespace

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1641]
Started seeing this on July 6 - steps to recreate:
* Create a new space
* Create a new Vert.X project ("add to space")
* Accept all defaults
* Observe that the project is created, its build pipeline is started, but no codebase is created
* No errors are reported to the user or logged in the Chrome browser console

![screenshot from 2017-07-06 09-32-23](https://user-images.githubusercontent.com/642621/27913564-895dc55c-622e-11e7-81bd-b0bcd64504bb.png)

**Comment by ldimaggi** [comment]
Seeing this same problem with multiple user accounts.

**Comment by corinnekrych** [comment]
@ldimaggi it should be fixed by https://github.com/fabric8-ui/fabric8-ui/pull/1638
