### ISSUE TITLE
Creating a new project in a space results in new builds being created for all other projects in the space

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1642]
Steps to recreate:
* Create a space, create a project in that space - observe the pipeline/build for that project:
![screenshot from 2017-07-06 11-16-00](https://user-images.githubusercontent.com/642621/27918625-854f2da2-623d-11e7-914c-09f31b94193c.png)

* Create a second project in the space - observe that a 2ns build/pipeline for the first project is also created:
![screenshot from 2017-07-06 11-18-29](https://user-images.githubusercontent.com/642621/27918675-ad29b50e-623d-11e7-8640-1c00dcf5f9b9.png)

And - observe that this second build for the first project is executed BEFORE the first build for the 2nd project:
![screenshot from 2017-07-06 11-20-40](https://user-images.githubusercontent.com/642621/27918718-c851f38c-623d-11e7-888f-a0b28d821050.png)

**Comment by ldimaggi** [comment]
Related to repository name issue: https://github.com/fabric8-ui/fabric8-ui/issues/1498

If all the patterns are deleted from the "repository name pattern" field - then creating a new project only results in that project being built. Is this the proper workaround?

**Comment by joshuawilson** [comment]
I thought this was fixed if you cleaned up your BC, right @jstrachan?

**Comment by maxandersen** [comment]
Closing this as it is now duplicated on openshiftio/openshift.io#360

**Comment by joshuawilson** [comment]
Why not close the one in openshiftio? The work is to be done here, right?

**Comment by maxandersen** [comment]
> Why not close the one in openshiftio? The work is to be done here, right?

No, this bug looks like a backend issue.
