### ISSUE TITLE
Pipeline fails while build is successful - the user might miss the error symbol as the pipeline phases stays green

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1646]
It's possible for a build to be successful, but the pipeline fails. The resulting pipeline display shows both red and green results - we should better highlight that the pipeline failed.

![screenshot from 2017-07-06 14-54-24](https://user-images.githubusercontent.com/642621/27928927-081ef3ea-625f-11e7-9890-8d5f1ceead37.png)

Log fragment follows:

```

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.804 s
[INFO] Finished at: 2017-07-06T18:45:41+00:00
[INFO] Final Memory: 12M/491M
[INFO] ------------------------------------------------------------------------
[Pipeline] sh
[osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA] Running shell script
Executing shell script inside container [maven] of pod [jenkins-slave-mvcm8-1f5tv]
Executing command: sh -c echo $$ > '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA@tmp/durable-aab9fd76/pid'; jsc=durable-053596687ba2418070239e64749ac522; JENKINS_SERVER_COOKIE=$jsc '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA@tmp/durable-aab9fd76/script.sh' > '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA@tmp/durable-aab9fd76/jenkins-log.txt' 2>&1; echo $? > '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA@tmp/durable-aab9fd76/jenkins-result.txt' 
cd "/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T5LMGXJA"
sh -c echo $$ > '/home/jenkins/workspace/osiotest314_july6a_master-UI254UKQTLZZP2P4YZWI42Y7XEVMOSXYHFXCI3PXFGZ5T[?1034hsh-4.2$ [Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code -2
Finished: FAILURE
```

**Comment by joshuawilson** [comment]
@jstrachan how can it fail and pass at the same time?

**Comment by jstrachan** [comment]
the status of a stage != the status of the build. 

From the log all the stages are green (see the 'SUCCESS') in the build log - thats the last stage. Then after all that the final build that returned an error. So the UI is totally correct - the stages all were green but the build failed right at the end.

I'll try figure out why though; as thats a tad wacky.

**Comment by ldimaggi** [comment]
This issue is related - https://github.com/fabric8-ui/fabric8-ui/issues/1648

**Comment by joshuawilson** [comment]
@jstrachan Is this something we should change in the UI? or is it good enough now. I'm asking because it was confusing to us. Maybe @catrobson can come up with a better way to display this so the user will understand.

**Comment by joshuawilson** [comment]
related to #1615

**Comment by catrobson** [comment]
@jstrachan Are we able to give the user some information about the problem with the build failure?  I think the user in this case is looking to understand why I am in a failure state, so we need some information to show.  If so, can I get an example of what that might look like so I can consider how to integrate it into the screen for these cases?

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#881
