### ISSUE TITLE
Create a new project - Secured Spring Boot Tomcat Quickstart - fails

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1660]
Steps to recreate:
* Create a new project - in either a new or existing space - select Secured Spring Boot Tomcat
* Project fails in rollout to stage

Error is: no openshift.yaml found

See attached build log file. 
[Secured_Spring_Boot_Tomcat_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1131505/Secured_Spring_Boot_Tomcat_log.txt)

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#392
