### ISSUE TITLE
Create a new project - Secured Vertx - Rest & Red Hat SSO Quickstart - fails

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1664]
Steps to recreate:
* In a new or existing space, create a new Quickstart project of type: Secured Vertx - Rest & Red Hat SSO
* Rollout to stage fails - error logged is:
```
[Pipeline] { (Rollout to Stage)
[Pipeline] kubernetesApply
no openshift.yml found
```

See attached build log.
[Secured_VertX_REST_RH_SSO_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1131850/Secured_VertX_REST_RH_SSO_log.txt)

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#393
