### ISSUE TITLE
Failures in staging should prevent deployment to run - but they aren't

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1666]
See attached screenshot - creating a new (Vert.x - CRUD) quickstart failed in staging. (A separate issue will be logged for this failure.)

The failure in staging did not prevent the app from being promoted to run. Shouldn't a failure to stage always abort the build pipeline? 

![screenshot from 2017-07-07 14-56-48](https://user-images.githubusercontent.com/642621/27972649-18527d4c-6325-11e7-88fd-d7540928d191.png)

**Comment by joshuawilson** [comment]
@jstrachan here is another for you.

**Comment by joshuawilson** [comment]
@rawlingsj do you know why this staging failure doesn't block the build?

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#877
