### ISSUE TITLE
Create a new project - Spring Boot CRUD - fails

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1668]
Steps to recreate:
* Create a new project - Select Spring Boot CRUD

Error raised is:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project july7: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

Build log attached.
[Spring_Boot_CRUD_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132178/Spring_Boot_CRUD_log.txt)

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#395
