### ISSUE TITLE
Create new project - WildFly Swarm - Health Checks - fails

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1673]
To recreate:
* In a new or existing space, create a new project from the WildFly Swarm - Health Checks quickstart

This error is logged:

```
[ERROR] Failed to execute goal on project july8: Could not resolve dependencies for project com.example:july8:war:1.0.1: The following artifacts could not be resolved: org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1, org.jboss.openjdk-orb:openjdk-orb:jar:8.0.4.Final: Could not find artifact org.glassfish:javax.el-impl:jar:3.0.1-b08-jbossorg-1 in nexus (http://central.maven.org/maven2/) -> [Help 1]
```

Build log is attached.
[Wildfly_Swarm_health_checks_log.txt](https://github.com/fabric8-ui/fabric8-ui/files/1132631/Wildfly_Swarm_health_checks_log.txt)

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#400
