### ISSUE TITLE
Newly provisioned user accounts are missing a "test" project

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1677]
For example, a new user account ("osiotest314") has these projects defined - there is no "test" project:

![screenshot from 2017-07-08 19-07-01](https://user-images.githubusercontent.com/642621/27990709-27791232-642d-11e7-88c5-f59bcde99d28.png)

**Comment by joshuawilson** [comment]
@aslakknutsen @jstrachan Do you know anything about this?

**Comment by ldimaggi** [comment]
@aslakknutsen @jstrachan @maxandersen @corinnekrych @qodfathr 

Was this an intentional change to drop the "test" project?  Or - is this another problem that only new users will see?

**Comment by jstrachan** [comment]
We were told to remove the test project to reduce the OSO footprint  - so now integration tests run in the 'foo' namespace rather than 'foo-test'
