### ISSUE TITLE
Importing existing code creates the project and codespace - but not a build pipeline

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1678]
If a user imports existing code - the codespace is created, but not the build pipeline.

**Comment by joshuawilson** [comment]
@ldimaggi are you still seeing this?
@jstrachan do you know what is causing this?

**Comment by ldimaggi** [comment]
Yes - this issue is still present.

**Comment by jstrachan** [comment]
got an example project thats been imported?

**Comment by rgarg1** [comment]
The issue is still reproducible. I used my brand new OSIO account today to import an untouched Vertx repo: https://github.com/rgargosiotest1/aug3a

The Pipelines were never started.

**Comment by jstrachan** [comment]
this is fixed now - just waiting to get to prod

**Comment by jstrachan** [comment]
its in prod

**Comment by ldimaggi** [comment]
Just tried this - using a repo that I forked from a test repo that Burr created - https://github.com/ldimaggi/vertx-eventbus

The import worked cleanly - the app was deployed to stage and run in the pipeline - the pipeline was correctly included in the OSIO UI.
