### ISSUE TITLE
Import repo wizard should show an error when no repos are selected

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1683]
In select repo, the multi-selection filtered list for repos does not show an error when no repo is selected. 
* actual
The wizard carries on silently to fail at codebase creation.
* expected
The wizard should show the error and disable the next button.

**Comment by corinnekrych** [comment]
fixed with https://github.com/fabric8io/fabric8-generator/pull/26

**Comment by joshuawilson** [comment]
Can we close it?
