### ISSUE TITLE
Running tests in Che workspace for project created from "Vert.X HTTP +  ConfigMap" workspace = Syntax error in test code

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1704]

**Comment by ldimaggi** [comment]
The same error as described in this issue is seen:
https://github.com/fabric8-ui/fabric8-ui/issues/1700

**Comment by ldimaggi** [comment]
Tests were run in the UI, from the Run->Test menu.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#406
