### ISSUE TITLE
Running tests in Che workspace for project created from "Vert.X HealthCheck" workspace = file not found error

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1706]

**Comment by ldimaggi** [comment]
The same exception is raised as is documented here:
https://github.com/fabric8-ui/fabric8-ui/issues/1694

**Comment by ldimaggi** [comment]
Tests were run in the UI, from the Run->Test menu.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#408
