### ISSUE TITLE
Duplicate pipelines created when user creates a new project

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1707]
See attached screenshot.

Steps to recreate:
* In a new space, with all github repos deleted, and all OpenShift assets removed for the user account,
create a new project from the Vert.X quickstart.
* Observe the duplicate pipelines

![screenshot from 2017-07-10 23-12-29](https://user-images.githubusercontent.com/642621/28049447-7ab1c572-65c5-11e7-8e59-f5cdd358ce9f.png)

**Comment by corinnekrych** [comment]
@ldimaggi today I'll work on https://github.com/fabric8-ui/fabric8-ui/issues/1593 let see if the removal of duplicate steps helps.

**Comment by joshuawilson** [comment]
I don't think they are related since this bug just started happening.

**Comment by jstrachan** [comment]
this is mostly fixed now. slightly long story; 

if we can't talk to the websockets on the kubernetes/openshift REST API we default to polling. The polling UI has a bug introducing duplicates. Its on my list of things to fix real soon...

However openshift.io should be using websockets so shouldn't need to poll so shouldn't have shown this issue. However that got broken briefly with configuration changes for kubernetes. Its fixed now though.

Though I have seen this duplicate issue show up now and again when using websockets; so lets leave this issue open until I nail the bug for polling + websockets....

**Comment by ldimaggi** [comment]
Note - over time - the number of duplicates continues to increase.

**Comment by burrsutter** [comment]
I saw this again on July 19th

**Comment by ldimaggi** [comment]
Actually - it seems to be a little worse now...

![screenshot from 2017-07-19 18-19-49](https://user-images.githubusercontent.com/642621/28392230-07ab0b60-6caf-11e7-9caa-28960bab09ed.png)
![screenshot from 2017-07-19 18-19-06](https://user-images.githubusercontent.com/642621/28392229-07a7c9b4-6caf-11e7-9d18-14f6650a581f.png)

**Comment by jstrachan** [comment]
fixed now in fabric8-runtime-console; just needs merging to fabric8-ui and releasing to prod

**Comment by jstrachan** [comment]
its now in fabric8-ui - we just need it released to production. @joshuawilson fancy doing the magic manual steps please?
