### ISSUE TITLE
Experimental Features direct link behavior

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ui#1719]
There are a few states that can happen for users accessing experimental features, so I have captured the expected behavior below:

User is direct linked into a experimental feature page, and they are not logged in.  Page should be shown to them with the experimental feature banner at the top.

User is direct linked into an experimental feature page, and they are logged in, but have not opted into experimental features.  Empty state is shown to them, and they have to opt into the experimental state to see the page they were trying to view.

User is direct linked into an experimental feature page, and they are logged in and have opted into experimental features.  Page is shown with experimental banner at the top.

**Comment by dgutride** [comment]
Fixed via #1721

**Comment by dgutride** [comment]
Closing upon deploy to production - work is complete @maxandersen

**Comment by maxandersen** [comment]
@dgutride i just tried and it seems to be working slightly better now for logged in user - but i'm getting 404 for pages like https://openshift.io/openshiftio/openshiftio/plan/detail/47728172-191a-4194-89fb-522008bf643a for anonymous users...shouldn't it at least say there is something here, but please login to see it ?

**Comment by dgutride** [comment]
![screenshot-openshift io-2017-07-13-18-07-19](https://user-images.githubusercontent.com/7306953/28189895-33480330-67f6-11e7-8cfc-81bcbb56b55d.png)

@catrobson @maxandersen  - this is what I see when I click on that link (I'm not logged in) - can you try again, maybe clear your cache and retry?

**Comment by maxandersen** [comment]
weird, works in incognito Chrome but on safari I get 404 even after clear cache/restart etc..

**Comment by dgutride** [comment]
@maxandersen - if you view other pages are you certain you are logged out?

**Comment by maxandersen** [comment]
@dgutride yes, no user logged in anywhere. But yeah with safari nothing actually works. not even when I try to login. 
really weird.

**Comment by dgutride** [comment]
@maxandersen  - does it work with regular chrome, too?

**Comment by maxandersen** [comment]
> @maxandersen - does it work with regular chrome, too?

looks like it.

**Comment by dgutride** [comment]
Moving to closed @maxandersen - Safari was upgraded to 10.1 (from 10.0.3)
