### ISSUE TITLE
_error has unlinked buttons and links

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ui#1724]
https://openshift.io/_error

Page has two buttons:
Take me home - should go to openshift.io/_home.  Make this button primary blue.
I'm feeling helpful, report the issue - remove this button because we don't have feedback implemented yet.

Links:
Add work item - remove this, we wouldn't know what space to go to
Iterations - remove this, we wouldn't know what space to go to
Spaces - navigate user to openshift.io/<username>
My dashboard - navigate to openshift.io/_home
Product Documentation - remove this

**Comment by catrobson** [comment]
@corinnekrych are there any variants to _error page that we should also check?

**Comment by corinnekrych** [comment]
@catrobson nope this is the one.
