### ISSUE TITLE
forge wizard validation messages no longer appear

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1725]
not sure if this is a regression of CSS styles or something but validation errors are no longer visible.

e.g. open the new quickstart wizard, type the name of a github repo that exists in your user account and hit tab so it validates; it should warn the project exists - but doesn't show anything. 

Note its still validating correctly - notice the Next/Finish buttons get disabled - its just the message is gone
![analyze_-_openshift_io](https://user-images.githubusercontent.com/30140/28152164-e6667718-6796-11e7-815f-c5404e72f70c.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 can you please take a look at this too.

**Comment by corinnekrych** [comment]
@joshuawilson @mindreeper2420 This is not a CSS issue. It's a bug on the forge UI wizard which swallowed the validation messages returned by http call in here: 
https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space-wizard/services/fabric8-app-generator.service.ts#L225
With the refactor of the wizard i think all validation error are swallowed
