### ISSUE TITLE
drop down / kebab menus broken

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1726]
seems the drop down menus no longer work - is this a CSS regression?

e.g. try any kebab menu on the Create > Pipelines / Applications / Environments page - none of them show anything any more.

**Comment by jstrachan** [comment]
seems the drop down combo box button is broken too - e.g. the combo box to pick a quickstart

**Comment by jstrachan** [comment]
FWIW this seems a recent regression, it wasn't there in `fabric8/fabric8-ui:vbd65fd8` which at the time of writing was 16 hours ago: https://hub.docker.com/r/fabric8/fabric8-ui/tags/

**Comment by mindreeper2420** [comment]
@jstrachan this should be fixed by PR https://github.com/fabric8-ui/fabric8-ui/pull/1728, which also addresses dropdowns.
