### ISSUE TITLE
App wizard app-generator-single-selection-dropdown does not displays drop down content when the dropdown is open

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1727]
![screenshot 2017-07-13 10 23 07](https://user-images.githubusercontent.com/1395710/28157337-75158656-67b6-11e7-8e39-a10798b707e4.png)
@mindreeper2420 when the `open` class is added, nothing more is displayed (although `li` content is there). 
Similar to the other issue https://github.com/fabric8-ui/fabric8-ui/issues/1725#event-1161942775 for kebab opened by @jstrachan 

@mindreeper2420 Please Help!!!

**Comment by jstrachan** [comment]
this relates to this issue too https://github.com/fabric8-ui/fabric8-ui/issues/1726 kebab menus were recently all broken too

**Comment by mindreeper2420** [comment]
@corinnekrych fix is in PR https://github.com/fabric8-ui/fabric8-ui/pull/1728. For some reason, simple transitions on the `.dropdown` class prevented anything in the wizard (and kebabs) from opening. I updated the code to have them be specific to `navbar-pf .dropdown`.
