### ISSUE TITLE
Need to increase request timeout between ui and core to make it work with idled che server

### ISSUE THREAD

**Issue by ibuziuk** [fabric8-ui/fabric8-ui#1745]
Che server idling is already promoted to prod which results in the following error when trying to create workspace against idled che-server:

```
Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
create:1 XMLHttpRequest cannot load https://api.openshift.io/api/codebases/2d3690fe-89f1-4bd9-8482-1eaac8848d3e/create. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://openshift.io' is therefore not allowed access. The response had HTTP status code 504.
```

Need to increase timeout to 5 mins for requests between ui & core.

We will be able to rollback to previous timeout only once async support will be in place[1]
[1] https://github.com/fabric8-services/fabric8-wit/issues/1506

**Comment by ibuziuk** [comment]
cc: @aslakknutsen @joshuawilson

**Comment by ibuziuk** [comment]
@joshuawilson @dlabrecq guys, will it be possible to get temp solution in place before async API will be implemented - making request to the endpoint again if timeout occurs (a few times) ? For now timeout happens after 30 seconds which is clearly not enough for che-server to start (In che-starter we have 3 minutes timeout for it). If there is no bandwidth for UI team to address this issue, could you please point me to the start workspace code and I will  provide PR for it ?

![image](https://user-images.githubusercontent.com/1461122/28334021-1a64b0c2-6bfa-11e7-9348-d92b0ae18a8e.png)

**Comment by joshuawilson** [comment]
We will work on it.

**Comment by ibuziuk** [comment]
@joshuawilson awesome, thank you

**Comment by dlabrecq** [comment]
@joshuawilson We may want to post a warning message instead, indicating it will try again. Please let me know if you want my help.

**Comment by joshuawilson** [comment]
@dlabrecq if you want to take this on that would be great.

**Comment by joshuawilson** [comment]
we have the status for che in the status widget, you might be able to read that

**Comment by ibuziuk** [comment]
@dlabrecq not sure if there is a need in warning message since expected che-server starting time is 2-3 mins now.

**Comment by joshuawilson** [comment]
@dlabrecq While we could wait for an event to make it usable. If that takes longer then a few minutes can you just set it to be inactive for 5 min. That will fix it for right now and then you can continue to look a more elegant solution.

**Comment by dlabrecq** [comment]
I was just worried the user might continue to click on the "open che" button/link if nothing appears to be happening. Maybe we can temporarily disable the button (and set a tooltip) while Che is starting?

**Comment by joshuawilson** [comment]
I think disable it until the timer is up works. The tooltip is a nice idea.

**Comment by dlabrecq** [comment]
See https://github.com/fabric8-ui/fabric8-ui/pull/1756

**Comment by ibuziuk** [comment]
@joshuawilson @dlabrecq could this issue be reopened ? Nothing seems to change - timeout happens after ~1 minute when trying to create workspace against idled che-server

**Comment by ibuziuk** [comment]
It looks like increasing timeout does not help - it still occurs after ~1 minute. I think this is related to routing for core. Router have a timeout set for request and it looks like we are hitting those timeouts - that could be a reason why increasing timeout on client side not working. To fix this issue there is a need to either increase timeout for core routes or making request to the endpoint again if timeout occurs (6 times) ?

**Comment by dlabrecq** [comment]
We can try adding a retry(n) statement to the request. If the request times out, it can try again n-number of times.

How long does it take before Che goes idle? Is there a way to force it to idle for testing? It's difficult to test a solution unless we can start with an idle Che.

**Comment by ibuziuk** [comment]
@dlabrecq che can be idled manually via `oc idle che-host` command - this is what I do for testing

**Comment by dlabrecq** [comment]
Please see https://github.com/fabric8-ui/fabric8-ui/pull/1780

**Comment by ibuziuk** [comment]
@joshuawilson @dlabrecq thank you guys. tested on https://fabric8-ui-fabric8-ui-pr-1780-fabric8-ui.badger.fabric8.io and the solution seems to work just fine :+1: 
Is it already on prod ? (on prod I still have problems with creating workspace against idled che-server)

**Comment by joshuawilson** [comment]
not on prod yet, I'll update prod

**Comment by ibuziuk** [comment]
@joshuawilson thank you!

**Comment by joshuawilson** [comment]
updated, please confirm and close

**Comment by joshuawilson** [comment]
well, I guess it is already closed :-P

**Comment by ibuziuk** [comment]
@joshuawilson  already closed, but confirm ;-)

**Comment by dlabrecq** [comment]
Glad the 'retry' is working. I was able to adjust the timeout shorter during testing, but 30 sec seemed to be the max, oddly.
