### ISSUE TITLE
import forge wizard doesn't pass in the labelSpace parameter (like the new quickstart project does)

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1762]
so the imported projects (BuildConfigs) don't get labelled with the space the user is in. 

Right now the ChoosePipelineStep isn't used for imports; which it probably should be really - which is the step which processes the labelSpace parameter - to let us associate a pipeline with imported projects. I've raised an issue here on that: https://github.com/fabric8io/fabric8-generator/issues/29

While this isn't a massive big deal just yet, we should add those labels soon - as I've seen some versions of fabric8-ui which filter out BC's with no space label.

**Comment by joshuawilson** [comment]
@jstrachan how much of this is related to https://github.com/fabric8-ui/fabric8-ui/issues/1770

**Comment by jstrachan** [comment]
its the same issue.

interestingly I just tried master of fabric8-ui and could not reproduce the issue; so dunno if @corinnekrych fixed this lately?

**Comment by jstrachan** [comment]
odd - so seems to work when debugging a locally running fabric8-ui, but the latest docker image still has this issue - so a bit stumped really

**Comment by joshuawilson** [comment]
and @qodfathr saw this issue on Friday last week in production.

**Comment by jstrachan** [comment]
I've not seen this work in prod or local fabric8 for a week or so - I've just no clue why master of fabric8-ui works great though

**Comment by corinnekrych** [comment]
@jstrachan I think this one https://github.com/fabric8-ui/fabric8-ui/issues/1762 could be closed. it must be fixed by: https://github.com/fabric8io/fabric8-generator/commit/2685aa6568f8f4e2b27b8fc344a7e68708e861a4 right?

**Comment by jstrachan** [comment]
yes! labelSpace is definitely passed now to import; its working great now
