### ISSUE TITLE
new quickstart wizard doesn't send across the labelSpace = nameOfCurrentSpace any more

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1770]
so that the generated pipeline (BuildConfig) doesn't get labelled with `space: nameOfCurrentSpace` which then makes the pipelines invisible on the Pipelines tab

**Comment by jstrachan** [comment]
The workaround to get back invisible pipelines in the UI: 

    oc label bc nameOfPipelinr space=nameOfSpace

**Comment by jyasveer** [comment]
This is also blocking us to see the stack reports from the pipeline page.

**Comment by joshuawilson** [comment]
@jstrachan do you have a plan to fix this? We can't expect new users to go in and make that kind of fix.

**Comment by joshuawilson** [comment]
@jstrachan if this isn't fixed, please reopen. Closing.
