### ISSUE TITLE
Add HTML/CSS Code Guidelines to Repo

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ui#1777]
Instead of referencing Code Guidelines that currently reside on fabric8-ux, I'd like to see them added directly to this repo for ease of reference and use.

Currently file location: https://github.com/fabric8-ui/fabric8-ux/blob/master/code-guidelines.md

@joshuawilson thoughts on this? Should it be extended to other repos that are consumed by fabirc8-ui as well?

**Comment by joshuawilson** [comment]
fabric8-ux lives within fabric8-ui, so I would say they can live in either repo and then everyone else points to them. I would not want them in multiple repos, because then we would have to maintain copies.
