### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by dgutride** [fabric8-ui/fabric8-ui#1785]
The platform code has quite a bit of unused code due to fast refactoring and shifting priorities.  We should remove it to make sure we can move quickly.

The list includes:

- team-membership-dialog/*
- templates/start-widget/*
- settings (still a live route but not accessible and should be removed)
- settings/profile/* & settings/tokens/*
- delete-account-dialog/*
- control/* (was a workaround component for localstorage problems)
- toggle/*

**Comment by joshuawilson** [comment]
We do have a user story for Settings in both Platform and Planner, so we might want to keep that.
