### ISSUE TITLE
Status Icon Does Not Show Rollup

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ui#1797]
In the Status drop down, when a status is anything other than green (check mark), it should appear in the header as such. Currently, the status icon in the header is always shown as the check mark, regardless of what the individual statuses are.

<img width="265" alt="screen shot 2017-07-26 at 11 57 24 am" src="https://user-images.githubusercontent.com/4032718/28630922-9eeb0da0-71f9-11e7-9be2-7c8b155b3dda.png">

**Comment by joshuawilson** [comment]
Some of the values need to be polled to get them, they aren't there until you open the menu. So it is not simple to just copy it to the top.
If we want to patch it, we could change the icon to the text "status".

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#867
