### ISSUE TITLE
Codebases Sync Issues

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ui#1802]
When deleting, moving or renaming a repo on GitHub, the changes are not synched to OSIO. Previous codebases still appear in the widget, but empty rows appear on the Codebases page for each repo that was deleted/moved/renamed existed. OSIO shows a notification that the repo in question cannot be found.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#866
