### ISSUE TITLE
Replace space-wizard with the angular patternfly wizard

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/fabric8-ui#182]

**Comment by joshuawilson** [comment]
@dlabrecq is this something you were planning on taking on in PF?

**Comment by joshuawilson** [comment]
related to fabric8-ui/ngx-widgets#46
related to #588

**Comment by dlabrecq** [comment]
We will port the Angular Patternfly wizard to pattenfly-ng, eventually. (We want to have feature parity at some point.) However, I don't have plans to port the Angular Patternfly wizard to ngx-widgets, considering the space wizard has already been implemented. Are there plans to introduce additional wizards any time soon?

**Comment by joshuawilson** [comment]
I think the question is could we use the Angular Patternfly in pf-ng to replace the space wizard we have in fabric8-ui.

**Comment by dlabrecq** [comment]
No, we cannot use Angular Patternfly because it's an Angular 1 component. I was asking because simply because we could change the priority of what components are added to patternfly-ng, first.

**Comment by dlabrecq** [comment]
Yes, but it will require a rewrite of the space wizard. The wizard in Angular Patternfly will also require a port to Angular 4. Now that we have some momentum going with patternfly-ng, I would suggest porting the wizard there, instead.

I was asking about the priority because we could change what order components are added to patternfly-ng. Now that we've performed the less conversion, we can begin using patternfly-ng shortly.

**Comment by joshuawilson** [comment]
I'm not ready to discuss priority yet, but I will say that once the less conversion is complete I would like us to switch from ngx-widgets to patternfly-ng where ever we can.

**Comment by mindreeper2420** [comment]
the last part of the Less conversion for the Wizard is in PR #1571.

**Comment by joshuawilson** [comment]
@mindreeper2420 while that is cool it is not what this issue is about. This is about creating a generic PatternFly wizard that we can swap out for the custom version we currently have.

**Comment by mindreeper2420** [comment]
@joshuawilson understood. You just linked this to 588, which is about the color variables, so I thought I would make a note of it here.

**Comment by dlabrecq** [comment]
The wizard has been ported to patternfly-ng, but don't believe we will use it to replace the space wizard. I believe @catrobson and @bdellascio are looking at a different design.

**Comment by catrobson** [comment]
@dlabrecq we decided that for now we would upgrade it to use PatternFly existing wizard until we're ready with a new model.

**Comment by corinnekrych** [comment]
@catrobson @dlabrecq I've renamed the issue "spike". I think we now know what we want to replace:
- we keep the sapce-wizard as it is.  to be redesign later to remove modal.
- we change app-generator wizard to reuse patternfly wizard.
we can create an other issue for that purpose when we do the redesign of quickstart/import flow.
