### ISSUE TITLE
Update to use the Async CheStarter API from Codebases

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#1825]
- fabric8-wit has provided 2 new endpoints - one for starting che server asynchronous & another for getting it's state
    `PATCH api/codebases/che/start`
    `GET api/codebases/che/state`  
- when user navigates to the "Codebases" view, UI first checks if che-server is running
- if che-server is running, all is good and the flow is the same to what we have right now
- if che-server is not running, UI first calls "start che-server" endpoint and begin to poll it's state until getting it is running or timeout occurs (3 mins)
- During che-server start-up "Create workspace" buttons are disabled and che status widget from drop-down is duplicated on the "Codebases" view with some message e.g. "Starting Che server - It might take a few minutes..."

cc: @aslakknutsen @ibuziuk 
ref: https://github.com/fabric8-services/fabric8-wit/issues/1506
ref: https://github.com/fabric8-services/fabric8-wit/pull/1559

**Comment by joshuawilson** [comment]
@dlabrecq when the PR on the backend gets merged is this something you want to do?

**Comment by dlabrecq** [comment]
Sure, I can do that. 

@catrobson I'm curious to hear your thoughts about disabling the "Create workspace" controls upon first entering the codebases page?

**Comment by joshuawilson** [comment]
@dlabrecq didn't mean to imply that you should do this without working through UX first. ;)

**Comment by catrobson** [comment]
+1 that if we can make it seamless, we should keep the create workspace enabled and just start that process at the end of the che startup process, and just show one overall "working on it" experience to the user on the workspace.  @dlabrecq we can work together and with @bdellasc on how to show the waiting event on workspace in a friendly way.

**Comment by joshuawilson** [comment]
What do you mean by "keep the create workspace enabled"?

**Comment by catrobson** [comment]
I'm opposing this statement - "During che-server start-up "Create workspace" buttons are disabled".  I think during che-server start-up we should leave the "Create workspace" button enabled, and just queue up any workspace creation request behind the startup behind the scenes- the user doesn't need to know that level of detail IMO.  The idea of starting up the che server when we navigate to the page is great so we can act faster on their requests, but we shouldn't deny them hitting the button if we're not ready.

**Comment by joshuawilson** [comment]
That means if they hit the button and it's not ready they will get an error.

**Comment by dlabrecq** [comment]
No, the user no longer hits an error. At least, not due to the old 30 sec request timeout.

If the user clicks the button, the spinner will start, tooltips are set, and the button is disabled appropriately. The user will simply wait, but Che will launch in a new window tab eventually.

The user won't see an error, unless Che times out itself, after 3 minutes.

**Comment by joshuawilson** [comment]
OK, that works for me. Just to be clear the button is active until you click it and then it become inactive if Che is not ready.

**Comment by catrobson** [comment]
Clicking the button should then initiate a "we're working to load your workspace" state (so yes, button is then replaced/disabled by this state) that tells the user what is going on in some way.  This is where we can work with visual design to refine the feedback to the user during this part of the process.

**Comment by joshuawilson** [comment]
I like it. Thanks for the detailed version. :)

**Comment by dlabrecq** [comment]
Sounds good to me!

**Comment by ibuziuk** [comment]
PR https://github.com/fabric8-services/fabric8-wit/pull/1559 has been merged
Some http status code details:
`PATCH api/codebases/che/start` 
 - 200 if che server is running and ready to handle requests (che server state info in the body)
-  202 if it che server has been started asynchronously (che server state info in the body)
 `GET api/codebases/che/state`
- 200 (che-server state info in the body)

 che-server state info = `{ "running": true / false }`

**Comment by burrsutter** [comment]
A screencast of the problem
https://screencast.com/t/DSO3hRWQ5T

**Comment by dlabrecq** [comment]
Fixed by PR #1954
