### ISSUE TITLE
Document of fabric8-ui wiki the space wizard

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1839]
in the wiki, give some information about:
* publish Mitch uml diagram
* add a desciption about runtime
* explain API with forge add-on
* link backend repos

**Comment by dgutride** [comment]
@corinnekrych - during a follow-on discussion about understanding which quick-starts are available, it was requested that we identify the source locations of each quick start listed in the wizard (github repo/fork) - can we include that in the documentation as well?  @burrsutter fyi

**Comment by corinnekrych** [comment]
Done here: https://github.com/fabric8-ui/fabric8-ui/wiki/Forge-Wizard

**Comment by corinnekrych** [comment]
@dgutride here is the doc on where to find boosters: https://github.com/fabric8-ui/fabric8-ui/wiki/Forge-Wizard#where-does-it-find-booster
