### ISSUE TITLE
Changing the name of a new space should remove the `already exist` error message 

### ISSUE THREAD

**Issue by sunix** [fabric8-ui/fabric8-ui#1850]
Having that

- osio user has a space `newspace` created
- osio user try to create a new space with the name `newspace`
- the creation wizard shows back the form with the error ` The GitHub repository newspace already exists! The following characters are accepted:  dashes, letters, numbers  and the name cannot start or end with a dash `

When

- osio user is modifying the field `name`

Then

- the error message is still displayed

This is confusing to the user as it feel like its changes did fix the error message. Would be nice to have this message disappeared once user modify the user.

![analyze - openshift io - google chrome_053](https://user-images.githubusercontent.com/650571/29076438-d6686b4a-7c55-11e7-9b63-c72f062f3052.png)

**Comment by joshuawilson** [comment]
this issue was listed several weeks ago at https://github.com/openshiftio/openshift.io/issues/382

**Comment by sunix** [comment]
@joshuawilson to me looks like a different issue.
