### ISSUE TITLE
Gather requirements & shared understanding for deleting a space

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ui#1852]
Discuss the full workflow and impact of deleting a space and come to agreement on what would be removed when deleting a space.

Verification Conditions:
* Met with @joshuawilson @aslakknutsen @dgutride @dlabrecq to discuss requirements and flow
* Document decisions of how delete should work
* Create stories for work on UX, UI, and Platform

**Comment by catrobson** [comment]
We've agreed that deleting a space will:

- Delete codebase links
- Delete workspaces
- "Clean" OpenShift for objects from that space, including:  Pipelines, Applications, Pods, Builds, Build Configs.

Deleting a space will not:

- Delete the github repository

**Comment by catrobson** [comment]
UX Design for deleting spaces has been captured in https://github.com/fabric8-ui/fabric8-ux/issues/573

**Comment by joshuawilson** [comment]
Since we met and have the designs in progress, I think we can close this. 
Please reopen if there is more to do.
