### ISSUE TITLE
Import wizard result displays [Object Object] due to forge addon API change

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1857]
![screenshot 2017-08-10 11 06 37](https://user-images.githubusercontent.com/1395710/29170264-fb3ae5d2-7dd7-11e7-92cc-5b5febd844d0.png)

**Comment by ldimaggi** [comment]
Duplicate of:  https://github.com/openshiftio/openshift.io/issues/483
