### ISSUE TITLE
on the Codebases page we should have the option to create a Pipeline for a Codebase

### ISSUE THREAD

**Issue by jstrachan** [fabric8-ui/fabric8-ui#1884]
folks can create codebases via a github URL, which is great. Folks may then want to then create a pipeline for it after the codebase has been created; so we should:

* know if a Codebase has an associated Pipeline or not and if not provide a kebab option on a Codebase to `Create Pipeline`

The `Create Pipeline` wizard would then work kinda like the `Import` wizard; only we already know the github coordinates so it could miss out the first 2 pages and go straight to the 'Pick Pipeline' page

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#864
