### ISSUE TITLE
Clean tenant deletes spaces but do not notified the header list 

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1900]
Scenario:
* go to profile, hit `clean tenant` button
* confirm deletion
* Actual: in the the header the list of recently visited spaces is not notified of the deletion. some "ghost" space are displayed
* expected: the space removed from clean tenant should also be removed in most recently visited list.

**Comment by joshuawilson** [comment]
@dgutride can you take this on?

**Comment by dgutride** [comment]
yep  - @joshuawilson - there is a bug in the runtime code that is breaking delete notifications if I wire them up, it is a bit more complicated unfortunately, I'm on it today, though

**Comment by joshuawilson** [comment]
thanks

**Comment by dgutride** [comment]
work is complete @corinnekrych
