### ISSUE TITLE
Stack Report Recommendations section overflowing

### ISSUE THREAD

**Issue by rhopp** [fabric8-ui/fabric8-ui#1903]
See screenshot:
![image](https://user-images.githubusercontent.com/1215011/29519870-3d8841be-867f-11e7-8e75-01a9f4cdef16.png)

**Comment by joshuawilson** [comment]
@mindreeper2420 can you take a look at this?

**Comment by joshuawilson** [comment]
I think this has been fixed. If you still see this as an issue please open a new issue on https://github.com/openshiftio/openshift.io
