### ISSUE TITLE
Profile picture should come from github

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ui#193]
The profile picture is not being carried in from github correctly:

![image](https://cloud.githubusercontent.com/assets/3739227/23274820/1977a7e0-f9d2-11e6-8694-0a772bd4e736.png)

**Comment by pmuir** [comment]
@catrobson I will need to borrow you or your account to reproduce.

**Comment by catrobson** [comment]
After discussion with Alexey, the current profile picture is being carried in from gravatar.  We don't ask the user before doing this, so its a bit hard for the user to identify where this mysterious profile picture came from.

Instead, I propose that we have a blank state image for the profile picture until we link to the user's github account.  Upon the github link, we will bring in the users profile picture from github.

Issue for UXD to create a blank state profile picture:  https://github.com/fabric8io/fabric8-ux/issues/224

**Comment by pmuir** [comment]
I'm not actually clear where the image is coming from now that we get the user record from developers.redhat.com.

However, @catrobson we now have the ability for the user to update their image by providing a new URL. We can't implement image storage atm. Can you think about how we present that UX?

**Comment by catrobson** [comment]
@alexeykazakov - can you describe where we currently stand with this?  Where are we getting the user profile image from by default before the user attempts to change it?

**Comment by catrobson** [comment]
I think there are a few options:
Option 1:  Pull the user profile image from one of the OATH accounts (github most likely for now, eventually we would use a Red Hat one used for login
Option 2: Only allow for user uploaded profile images.

If we go the way of Option 2, it might be work we throw away as we get a proper "Red Hat Account" set up with picture, profile information, etc.  I'm not sure if there is a clean and clear way to do Option 1 for now - I need some technical feasibility and constraints to work with on the design if we go with Option 1.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#934
