### ISSUE TITLE
Unit test takes longer to run

### ISSUE THREAD

**Issue by corinnekrych** [fabric8-ui/fabric8-ui#1934]
Prior to this [commit to introduce runtime console](https://github.com/fabric8-ui/fabric8-ui/commit/f6bde5ea7249f4bf686c2bdcdd6648183e57fa9b) tests take
* 1.467 secs to run
* start date: 13:29:51 end date 13:31:29 of 1min38s to load and run

After, tests take: 
* 27.548 secs to run (which is ok as runtime-console comes with more unit tests
 * start date: 13:23:01 end date 13:27:12 of 4min11s to load and run

I notice the PR on runtime-console remove the webpack plugin https://github.com/s-panferov/awesome-typescript-loader (a plugin to speed up TS compilation).  See this [commit](https://github.com/fabric8-ui/fabric8-ui/commit/11427410d0e0195251bfbee43ca21bc0bf6cd27b)
@joshuawilson not sure why we removed it.

**Comment by joshuawilson** [comment]
That was in runtime-console but wasn't needed in the merger. If you think it is needed, try adding it and see what it does.
