### ISSUE TITLE
Update stylelint-webpack-plugin package

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ui#1986]
The stylelint-webpack-plugin package will need to be updated in order to properly rebuild after a style failure when `npm start` is run. Currently, the build fails completely, causing the user to have to restart their build in order to re-lint any changes to `.less` files.

The is currently a PR in the [stylelint-webpack-plugin](https://github.com/JaKXz/stylelint-webpack-plugin) repo (number 112) that addresses this issue. Once that PR is merged, then we can update our package version.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#858
