### ISSUE TITLE
Need comparative comparison between the webpack-config files 

### ISSUE THREAD

**Issue by debloper** [fabric8-ui/fabric8-ui#2120]
There are several webpack config files building the project in different manner and for different purpose. But except for the config file naming, there seems to be no documentation about the differences between them or the exact purpose of needing to have these many configs.

It seems to me that a bootstrapper script that sets necessary env_vars, then only a handful of configs could/should be able to emulate all the behaviors all these configs are trying to achieve, and that'd be a better, more scalable solution.

If one _really_ has to keep on adding more and more build templates, at least knowing which one is most vanilla (and then tweaking it) would help. I've tried diff'ing them but that's not a very good way to understand the differences between them, nor do I suggest others to have to use that kind of approach for practical purpose.

**Comment by joshuawilson** [comment]
Webpack is an advanced bundling system. It is not used for builds. The alternative is SystemJS. Each config has the name in it for what it is for. 
 - `webpack.common.js` is the shared configs
 - `webpack.dev.js` is run when you use `npm start`
 - `webpack.test.js` is used when you use `npm test`
 - `webpack.prod.js` is used when you use `npm build`

Any others can largely be ignored unless you know what they do. 

While webpack may appear complex at first, it is a very elegant solution to a complex issue. Based on the above, what are you asking for?

**Comment by debloper** [comment]
My complain wasn't against webpack in itself. I see that as a tool, and as long as it's best at what it does, I'm cool with that. My ask was there seems to be lack of contexts (can't call that documentation, but can very well be) of how we're using it for our purpose.

It seems to be a limited knowledge how they're rigged and can practically only be obtained that information by asking specific person(s). Which isn't scalable at all. Some things are done differently than norm, and without any explanation for why is it that way.

I'm giving abstract summaries on purpose, let me know if you'd rather prefer specific examples.

**Comment by joshuawilson** [comment]
I'm not sure about running it on docker-compose. But `dev` and `prod` should both provide the configs needed to run it. The main difference is that prod should be minified and ugly for size, dropping anything not needed to run. While dev gives you everything we can think of to find and track down issues in the code.

Webpack is a very active community and accepts PRs. Using it is like any other tool, if you have never used it you would not know what it does or how it works. If you are trying to use it and want to document what you find, that would be great.

**Comment by debloper** [comment]
I'm sorry Joshua if I'm having trouble to get my point across.

My complain (if you think there is one, by the tone of it) isn't against webpack, or having to use it (or the lack there of), or a better alternative to that etc.

My proposition was, what's the difference between the configs, make it clearer to the ones using it. Doesn't matter that person has previous experience with webpack or not. To give an example from your last comment itself (which adds some of the details I was seeking), it'd be like:

- Config for `dev` build:
  - Build artifacts aren't minified+uglified
  - Verbose logging enabled for tracking causation of issues
  - Build size and generated artifacts aren't optimized for peerformance
- Config for `prod` build:
  - Generates minified+uglified artifacts, optimized for deployment
  - Logging disabled
- Config for 

If this ^ helps understand the point I'm trying to make. Essentially meaning, one not needing to extensively read the config files to understand the tidbits of differences (given, some are predictable and obvious, but not all of it). Thanks.

**Comment by joshuawilson** [comment]
Thanks @debloper that makes a lot of sense. I'll look at adding something along those lines.

**Comment by joshuawilson** [comment]
updated webpack
