### ISSUE TITLE
Menubar duplicates itself when toolbar for space setting is activated

### ISSUE THREAD

**Issue by fabifrank** [fabric8-ui/fabric8-ui#2144]
When opening the toolbar for the space settings within a space (url `testspace/settings`) and then click on `Analyze` for example the whole menubar duplicates itself to the right, so each button (`Analyze`, `Plan` ... ) exists twice or more. Only the most right barlist has active links.

**Comment by joshuawilson** [comment]
This is a duplicate of https://github.com/openshiftio/openshift.io/issues/1128.
This has been fixed. Please try a hard refresh (ctrl + shft + r) or open in incognito mode. 
I just checked it and it appears fixed. Please verify and let us know.

**Comment by fabifrank** [comment]
Fixed!
