### ISSUE TITLE
Update NPM Script

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ui#2175]
Update the `npm run reinstall` script to swap out `npm cache clean` for `npm cache verify`, in accordance with the new npm@5 configuration.

Currently, running `npm run reinstall` throws the following error
```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
```

**Comment by joshuawilson** [comment]
Yup, making the change through all the repos and building up to this one. Thanks.

**Comment by mindreeper2420** [comment]
outdated - closing
