### ISSUE TITLE
View Encapsulation - Consuming Modules

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-ui#2228]
Discuss View Encapsulation and whether Platform should be on, how to consume modules that do or do not have it turned on, etc.

**Comment by mindreeper2420** [comment]
Has there been a decision on turning this on or off, or even how to enforce proper styling (which is a primary concern), across modules that OSIO consumes?

**Comment by joshuawilson** [comment]
We have not discussed it more then a few minutes in the monday meeting. If you really want to track this, please repost it to https://github.com/openshiftio/openshift.io
