### ISSUE TITLE
Better way to handle displaying the default context

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/fabric8-ui#272]
Right now this is hardcoded to display for `/home` which may or may not be a problem.

**Comment by joshuawilson** [comment]
@fabric8io/uxd please review

**Comment by joshuawilson** [comment]
To be clear the default is no context, now using /_home.  
When in a context the default is the Analyze page with the URL of <user>/<space>. 

What is the desired change?

**Comment by catrobson** [comment]
I'm not clear what the problem is - is it that the url is just generically _home rather then something like crobson/home?

**Comment by joshuawilson** [comment]
I'm not sure, waiting on @pmuir.
