### ISSUE TITLE
Create Error page

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-ui#536]
We need to handle Error when pages don't load. 

Use this design. https://redhat.invisionapp.com/share/VTB0FR05Z

**Comment by catrobson** [comment]
There are additional error page situations that you can see here:  https://redhat.invisionapp.com/share/UQB3HEXFN

**Comment by joshuawilson** [comment]
@catrobson since all the pages look the same except for the text, I thought we could change that on the fly as needed.

**Comment by catrobson** [comment]
Yup - makes sense to me @joshuawilson

**Comment by joshuawilson** [comment]
We have the error page but we need the flow that gets a user to it. In most cases if something doesn't exist we redirect them. 
What flows would bring a user to an error page.

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#929
