### ISSUE TITLE
Can't remove a codebase

### ISSUE THREAD

**Issue by cctrieloff** [fabric8-ui/fabric8-ui#552]
[Screencast from 04-06-2017 12:53:03 PM.webm.zip](https://github.com/fabric8io/fabric8-ui/files/903348/Screencast.from.04-06-2017.12.53.03.PM.webm.zip)

**Comment by dlabrecq** [comment]
FYI, the APIs don't support deleting a codebase, so the feature is disabled in the codebases page. I would also like the ability to delete a space.

**Comment by joshuawilson** [comment]
@qodfathr @pmuir @aslakknutsen will we be allowed to remove a codebase?

**Comment by cctrieloff** [comment]
Can we edit them as an alternate to correct bad URL's for example?

**Comment by qodfathr** [comment]
Yes, you should be able to remove a codebase. Of concern is that if having at least one codebase listed is the only way to manipulate workspaces, that would be a problem (hence why workspaces probably need their own management screen).

It is not unreasonable to have a Space with no codebases -- e.g., that's essentially what Trello is.

**Comment by cctrieloff** [comment]
Why do you need a workspace without a code base?  I don't see that as a
limitation.

**Comment by qodfathr** [comment]
@cctrieloff I was thinking this:

1. Have a codebase  (via new Space, import, etc.)
2. Create a workspace
3. Remove the codebase
4. ??? How do I deal with the workspace created in step 2? How do I see it? Deprovision it? etc.

**Comment by cctrieloff** [comment]
We should delete the workspace when you remove the codebase. The system
should clean that up automatically.

Carl.

**Comment by joshuawilson** [comment]
@aslakknutsen is this something that you could do on the backend?

**Comment by qodfathr** [comment]
@cctrieloff but codebases are not associated 1:1 with workspaces. i.e., I may have 5 codebases and only one workspace which I end up bouncing between them (e.g. need to do that on Free). There are so many potential use cases, that I'd be very concerned about not having some sort of workspace management screen. Maybe not a priority for this month, but probably something that needs to get addressed in May.

**Comment by joshuawilson** [comment]
@qodfathr I might be mistaken but I thought you could only run one workspace at a time but each was directly associated with a codebase. As far as i remember, Che doesn't really work in a way for you to use different codebases with the same workspace.

**Comment by joshuawilson** [comment]
A workspace is a docker image that is built based on the stack the codebase needs. So if you have a Java codebase, then the workspace needs to have Java installed. Whereas, if it is a Node project then you don't want Java installed but it will have Node.

**Comment by cctrieloff** [comment]
right now they 1:1 and our UX etc oly assumes a 1:1 mapping. Let's auto
clean up the resources for now. One day if we decide to change the
relationship we can look at more options then.  I would prefer to be more
aggressive in clean up as we pay for any orphaned resources.

Carl.

**Comment by joshuawilson** [comment]
@dlabrecq please follow up on this. We need to be able to clean up the codebases.

**Comment by dlabrecq** [comment]
The codebases UI has a disabled option to delete a codebase; however, the Restful API does not support it. When the API has been implemented, we can enable the feature in the UI.

**Comment by catrobson** [comment]
We decided this morning that we will remove this option from the kabob in the UI until the API has been created to reduce confusion for users.

**Comment by dlabrecq** [comment]
Created PR https://github.com/fabric8-ui/fabric8-ui/pull/1869 to omit the disabled option.
