### ISSUE TITLE
PATCH /api/users called 8 times on page load

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8-ui/fabric8-ui#591]

**Comment by alexeykazakov** [comment]
is it /api/users or /api/users/:userID?
/api/users should not be used at all! :)

**Comment by alexeykazakov** [comment]
Ah, didn't notice you are talking about PATCH. Not GET.

**Comment by aslakknutsen** [comment]
@alexeykazakov Tho, unsure why this call is actually to PATCH the /api/users Collection endpoint, as oppose to the /api/user Resource. Make little sense.

**Comment by sbose78** [comment]
@aslakknutsen Just checked the requests in the browser console - 
Looks like the UI is making PATCH request to update `contextInformation`  ( stuff like recent spaces, etc )

@pmuir Any way we could bring down the number of requests from 8 ?

**Comment by joshuawilson** [comment]
@dgutride please take a look at this.

**Comment by dgutride** [comment]
User PATCH is now called twice on each navigation between spaces or context switch - this updates recent context information and recent space information.  Moving to closed as it no longer happens 8 times.
