### ISSUE TITLE
Consider moving the <header> element back inside the header component

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/fabric8-ui#72]
https://github.com/fabric8io/fabric8-ui/pull/60 moved it out, but we should consider moving it back in.

**Comment by joshuawilson** [comment]
I agree, that the header, main, and footer elements belong in the components that generate them. 

@mitchharpur what is the reason to have them outside of their controlling components?

**Comment by joshuawilson** [comment]
@mindreeper2420 @dgutride @dlabrecq what do you guys think about this. Please reference the code and discussion in the PR #60

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#937

**Comment by dlabrecq** [comment]
The app.component.html file references the header tag like so:

<header>
  <alm-app-header></alm-app-header>
</header>

It would be easy enough to move the tag to the header component.
