### ISSUE TITLE
Logging in with Firefox on RHEL7 presents the user with a blank screen

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#762]
his happens at the 18 second mark of the referenced screencast:

https://drive.google.com/open?id=0B1s-ZoxD8FjUcmRqSlpUQXBzT3M

This seems to be limited to RHEL7.

**Comment by joshuawilson** [comment]
I can't see the video. Does the UI eventually appear? If that is the case, I have noticed this as a bug that was fixed but needs a hard refresh to clear out.

**Comment by ldimaggi** [comment]
Sorry - can you see this link:

https://drive.google.com/a/redhat.com/file/d/0B1s-ZoxD8FjUcmRqSlpUQXBzT3M/view?usp=sharing

No - the app never loads for me with Firefox 45.4.0 on RHEL 7

**Comment by joshuawilson** [comment]
@ldimaggi is this still an issue?

**Comment by ldimaggi** [comment]
YES it is!  ;-)

**Comment by joshuawilson** [comment]
This issue was moved to openshiftio/openshift.io#927
