### ISSUE TITLE
No error message for duplicate Area's name 

### ISSUE THREAD

**Issue by naina-verma** [fabric8-ui/fabric8-ui#921]
No error message for duplicate Area's name 
![screenshot from 2017-04-20 17-09-59](https://cloud.githubusercontent.com/assets/19172870/25229005/34eedb6a-25ec-11e7-8f4a-16955a051b15.png)

video link: https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COQ0hiRndQNkQ4Ukk/view?usp=sharing

`{"errors":[{"code":"bad_parameter","detail":"Bad value for parameter 'name \u0026 space_id \u0026 path': 'fabric8-planner \u0026 e99e01b1-ee7a-4893-8237-cfa838622a3c \u0026 /6add3ebc-e541-48dd-90bc-894497ce008a' (expected: 'unique')","status":"400","title":"Bad parameter error"}]}
{"errors":[{"code":"unknown_error","detail":"pq: Could not complete operation in a failed transaction","status":"500","title":"Unknown error"}]}
`

**Comment by joshuawilson** [comment]
This doesn't allow you to proceed but there is still no explanation given to the user. 
@kylebuch8 Can you take this one on?

**Comment by kylebuch8** [comment]
I've issued PR #1616 for this. Looks like we need to either make the error message more generic or get an update to the API to provide a more specific error message.

**Comment by dgutride** [comment]
This is dependent on the API being updated as outlined here:  https://github.com/openshiftio/openshift.io/issues/312
