### ISSUE TITLE
Remove docker related files that are not used

### ISSUE THREAD

**Issue by humaton** [fabric8-ui/fabric8-ui#97]
remove docker-compose.yml and Dockerfiles.

**Comment by sbose78** [comment]
Following files are not needed, and maybe removed.

- docker-compose.yml
- Dockerfile

**Comment by sbose78** [comment]
@humaton 

This is the script https://github.com/fabric8io/fabric8-ui/blob/master/cico_build_deploy.sh which should work for deploying in a container. This is currently not working because of failure of `npm run build:prod` , but the deploy stuff is already in there.

**Comment by humaton** [comment]
Thanks for the info, so it is/will be used in production. My question is can we make it run in development?
Not every one is in favor of running npm install on main OS.

**Comment by joshuawilson** [comment]
I think that @kbsingh said that we should keep these docker files so that we can run it in docker locally.

@kbsingh can you please confirm.

**Comment by joshuawilson** [comment]
@kbsingh @jstrachan do we need these files for running docker locally?

**Comment by jstrachan** [comment]
Letting folks use docker to run locally sounds fine - though they won't be used for CI/CD. 

Maybe the ReadMe needs to be more clear they are only for local development?
